[General]
; Set to true to skip all boot intros
; (SCEA Presents, Copyright, Naughty Dog)
skip_intro = false

[Adventure]
; Set to true to skip mask hints in adventure mode
skip_hints = false

[Vehicle]
; Speed stat multiplier in percent (100 = default, in-game range 10-200)
speed_stat_multiplier = 100