#ifndef GAME_INCLUDES_H
#define GAME_INCLUDES_H

#define REBUILD_PS1

#include <common.h>

#include "game/TEST_226.c"
#include "game/TEST_DrawSkybox.c"
#include "game/TEST_DrawInstances.c"
#include "game/TEST_ConvertRotToMatrix.c"
#include "game/TEST_ThTickRunBucket.c"
#include "game/TEST_ThTickSetAndExec.c"

#define ConvertRotToMatrix TEST_ConvertRotToMatrix
#define ThTick_SetAndExec  TEST_ThTickSetAndExec

#define SquareRoot0_stub   SquareRoot0

#include "game/MAIN/MAIN_AAA_BigBlock1.c"

#include "game/CAMERA/CAM_01_ClearScreen.c"
#include "game/CAMERA/CAM_02_Init.c"
#include "game/CAMERA/CAM_04_Path_GetNumPoints.c"
#include "game/CAMERA/CAM_05_Path_Move.c"
#include "game/CAMERA/CAM_06_StartOfRace.c"
#include "game/CAMERA/CAM_10_ProcessTransition.c"
#include "game/CAMERA/CAM_16_SetDesiredPosRot.c"

#include "game/CDSYS/CDSYS_00_Init.c"
#include "game/CDSYS/CDSYS_01_GetFilePosInt.c"
#include "game/CDSYS/CDSYS_02_SetMode_StreamData.c"
#include "game/CDSYS/CDSYS_03_SetMode_StreamAudio.c"
#include "game/CDSYS/CDSYS_04_SetXAToLang.c"
#include "game/CDSYS/CDSYS_05_XaCallbackCdSync.c"
#include "game/CDSYS/CDSYS_06_XaCallbackCdReady.c"
#include "game/CDSYS/CDSYS_07_SpuCallbackIRQ.c"
#include "game/CDSYS/CDSYS_08_SpuCallbackTransfer.c"
#include "game/CDSYS/CDSYS_09_SpuEnableIRQ.c"
#include "game/CDSYS/CDSYS_10_SpuDisableIRQ.c"
#include "game/CDSYS/CDSYS_11_SpuGetMaxSample.c"
#include "game/CDSYS/CDSYS_12_XAGetNumTracks.c"
#include "game/CDSYS/CDSYS_13_XASeek.c"
#include "game/CDSYS/CDSYS_14_XAGetTrackLength.c"
#include "game/CDSYS/CDSYS_15_XAPlay.c"
#include "game/CDSYS/CDSYS_16_XAPauseRequest.c"
#include "game/CDSYS/CDSYS_17_XAPauseForce.c"
#include "game/CDSYS/CDSYS_18_XAPauseAtEnd.c"

#include "game/COLL/COLL_00_LevModelMeta.c"

#include "game/CTR/CTR_00_Box_DrawWirePrims.c"
#include "game/CTR/CTR_01_Box_DrawWireBox.c"
#include "game/CTR/CTR_02_Box_DrawClearBox.c"
#include "game/CTR/CTR_03_Box_DrawSolidBox.c"
#include "game/CTR/CTR_04_CycleTex_LEV.c"
#include "game/CTR/CTR_05_CycleTex_Model.c"
#include "game/CTR/CTR_06_CycleTex_AllModels.c"
#include "game/CTR/CTR_11_ErrorScreen.c"

#include "game/DebugFont/DebugFont_0_Init.c"
#include "game/DebugFont/DebugFont_1_DrawNumbers.c"

#include "game/DecalFont/DecalFont_0_GetLineWidthStrlen.c"
#include "game/DecalFont/DecalFont_1_GetLineWidth.c"
#include "game/DecalFont/DecalFont_2_DrawLineStrlen.c"
#include "game/DecalFont/DecalFont_3_DrawLine.c"
#include "game/DecalFont/DecalFont_4_DrawLineOT.c"
#include "game/DecalFont/DecalFont_5_DrawMultiLineStrlen.c"
#include "game/DecalFont/DecalFont_6_DrawMultiLine.c"

#include "game/DecalGlobal/DecalGlobal_1_Clear.c"
#include "game/DecalGlobal/DecalGlobal_2_Store.c"

#include "game/DecalHUD/DecalHUD_0_DrawPolyFT4.c"
#include "game/DecalHUD/DecalHUD_1_DrawWeapon.c"
#include "game/DecalHUD/DecalHUD_2_DrawPolyGT4.c"
#include "game/DecalHUD/DecalHUD_3_Arrow2D.c"

#include "game/Display/DISPLAY_2_Swap.c"

#include "game/DotLights/DotLights_1_AudioAndVideo.c"

#include "game/DropRain/DropRain_0_MakeSound.c"
#include "game/DropRain/DropRain_1_Reset.c"

#include "game/ElimBG/ElimBG_0_SaveScreenshot_Chunk.c"
#include "game/ElimBG/ElimBG_1_SaveScreenshot_Full.c"
#include "game/ElimBG/ElimBG_2_Activate.c"
#include "game/ElimBG/ElimBG_3_ToggleInstance.c"
#include "game/ElimBG/ElimBG_4_ToggleAllInstances.c"
#include "game/ElimBG/ElimBG_5_HandleState.c"
#include "game/ElimBG/ElimBG_6_Deactivate.c"

#include "game/GAMEPAD/GAMEPAD_00_Init.c"
#include "game/GAMEPAD/GAMEPAD_01_SetMainMode.c"
#include "game/GAMEPAD/GAMEPAD_02_ProcessState.c"
#include "game/GAMEPAD/GAMEPAD_03_PollVsync.c"
#include "game/GAMEPAD/GAMEPAD_04_GetNumConnected.c"
#include "game/GAMEPAD/GAMEPAD_05_ProcessHold.c"
#include "game/GAMEPAD/GAMEPAD_06_ProcessSticks.c"
#include "game/GAMEPAD/GAMEPAD_07_ProcessTapRelease.c"
#include "game/GAMEPAD/GAMEPAD_08_ProcessMotors.c"
#include "game/GAMEPAD/GAMEPAD_09_ProcessAnyoneVars.c"
#include "game/GAMEPAD/GAMEPAD_10_JogCon1.c"
#include "game/GAMEPAD/GAMEPAD_11_JogCon2.c"
#include "game/GAMEPAD/GAMEPAD_12_ShockFreq.c"
#include "game/GAMEPAD/GAMEPAD_13_ShockForce1.c"
#include "game/GAMEPAD/GAMEPAD_14_ShockForce2.c"

#include "game/GAMEPROG/GAMEPROG_01_ResetHighScores.c"
#include "game/GAMEPROG/GAMEPROG_02_CheckGhostsBeaten.c"
#include "game/GAMEPROG/GAMEPROG_03_NewProfile_OutsideAdv.c"
#include "game/GAMEPROG/GAMEPROG_05_NewProfile_InsideAdv.c"
#include "game/GAMEPROG/GAMEPROG_08_NewGame_OnBoot.c"
#include "game/GAMEPROG/GAMEPROG_09_GetPtrHighScoreTrack.c"

#include "game/GHOST/GhostReplay_00_ThTick.c"
#include "game/GHOST/GhostReplay_01_Init1.c"
#include "game/GHOST/GhostReplay_02_Init2.c"

#include "game/GHOST/GhostTape_00_Start.c"
#include "game/GHOST/GhostTape_01_End.c"
#include "game/GHOST/GhostTape_02_WriteMoves.c"
#include "game/GHOST/GhostTape_03_WriteBoosts.c"
#include "game/GHOST/GhostTape_04_Destroy.c"

#include "game/HOWL/h01_CountSounds.c"
#include "game/HOWL/h02_OtherFX_Play.c"
#include "game/HOWL/h03_OtherFX_Play_Echo.c"
#include "game/HOWL/h04_OtherFX_Play_LowLevel.c"
#include "game/HOWL/h05_OtherFX_Modify.c"
#include "game/HOWL/h06_OtherFX_Stop1.c"
#include "game/HOWL/h07_OtherFX_Stop2.c"
#include "game/HOWL/h08_EngineAudio_InitOnce.c"
#include "game/HOWL/h09_EngineAudio_Recalculate.c"
#include "game/HOWL/h10_EngineAudio_Stop.c"
#include "game/HOWL/h11_SetReverbMode.c"
#include "game/HOWL/h12_CseqMusic_Start.c"
#include "game/HOWL/h13_CseqMusic_Pause.c"
#include "game/HOWL/h14_CseqMusic_Resume.c"
#include "game/HOWL/h15_CseqMusic_ChangeVolume.c"
#include "game/HOWL/h16_CseqMusic_Restart.c"
#include "game/HOWL/h17_CseqMusic_ChangeTempo.c"
#include "game/HOWL/h18_CseqMusic_AdvHubSwap.c"
#include "game/HOWL/h19_CseqMusic_Stop.c"
#include "game/HOWL/h20_CseqMusic_StopAll.c"
#include "game/HOWL/h21_Bank_ResetAllocator.c"
#include "game/HOWL/h22_Bank_Alloc.c"
#include "game/HOWL/h23_Bank_AssignSpuAddrs.c"
#include "game/HOWL/h24_Bank_Destroy.c"
#include "game/HOWL/h25_Bank_ClearInRange.c"
#include "game/HOWL/h26_Bank_Load.c"
#include "game/HOWL/h27_Bank_DestroyLast.c"
#include "game/HOWL/h28_Bank_DestroyUntilIndex.c"
#include "game/HOWL/h29_Bank_DestroyAll.c"
#include "game/HOWL/h30_howl_InstrumentPitch.c"
#include "game/HOWL/h31_howl_InitGlobals.c"
#include "game/HOWL/h32_howl_ParseHeader.c"
#include "game/HOWL/h33_howl_ParseCseqHeader.c"
#include "game/HOWL/h34_howl_LoadHeader.c"
#include "game/HOWL/h35_howl_SetSong.c"
#include "game/HOWL/h36_howl_LoadSong.c"
#include "game/HOWL/h37_howl_ErasePtrCseqHeader.c"
#include "game/HOWL/h38_howl_GetNextNote.c"
#include "game/HOWL/h39_cseq_opcode01_noteoff.c"
#include "game/HOWL/h40_cseq_opcode03.c"
#include "game/HOWL/h41_howl_InitChannelAttr_Music.c"
#include "game/HOWL/h42_cseq_opcode_from06and07.c"
#include "game/HOWL/h43_cseq_opcode05_noteon.c"
#include "game/HOWL/h44_cseq_opcode06.c"
#include "game/HOWL/h45_cseq_opcode07.c"
#include "game/HOWL/h46_cseq_opcode08.c"
#include "game/HOWL/h47_cseq_opcode09.c"
#include "game/HOWL/h48_cseq_opcode0a.c"
#include "game/HOWL/h49_SongPool_FindFreeChannel.c"
#include "game/HOWL/h50_SongPool_CalculateTempo.c"
#include "game/HOWL/h51_SongPool_ChangeTempo.c"
#include "game/HOWL/h52_SongPool_Start.c"
#include "game/HOWL/h53_SongPool_Volume.c"
#include "game/HOWL/h54_SongPool_AdvHub1.c"
#include "game/HOWL/h55_SongPool_AdvHub2.c"
#include "game/HOWL/h56_SongPool_StopCseq.c"
#include "game/HOWL/h57_SongPool_StopAllCseq.c"
#include "game/HOWL/h58_howl_Disable.c"
#include "game/HOWL/h59_UpdateChannelVol_EngineFX.c"
#include "game/HOWL/h60_UpdateChannelVol_OtherFX.c"
#include "game/HOWL/h61_UpdateChannelVol_Music.c"
#include "game/HOWL/h62_UpdateChannelVol_EngineFX_All.c"
#include "game/HOWL/h63_UpdateChannelVol_Music_All.c"
#include "game/HOWL/h64_UpdateChannelVol_OtherFX_All.c"
#include "game/HOWL/h65_howl_VolumeGet.c"
#include "game/HOWL/h66_howl_VolumeSet.c"
#include "game/HOWL/h67_howl_ModeGet.c"
#include "game/HOWL/h68_howl_ModeSet.c"
#include "game/HOWL/h69_OptionsMenu_TestSound.c"
#include "game/HOWL/h70_Smart_EnterCriticalSection.c"
#include "game/HOWL/h71_Smart_ExitCriticalSection.c"
#include "game/HOWL/h72_Channel_SetVolume.c"
#include "game/HOWL/h73_Channel_FindSound.c"
#include "game/HOWL/h74_Channel_AllocSlot_AntiSpam.c"
#include "game/HOWL/h75_Channel_AllocSlot.c"
#include "game/HOWL/h76_Channel_SearchFX_EditAttr.c"
#include "game/HOWL/h77_Channel_SearchFX_Destroy.c"
#include "game/HOWL/h78_Channel_DestroyAll_LowLevel.c"
#include "game/HOWL/h79_Channel_ParseSongToChannels.c"
#include "game/HOWL/h80_Channel_UpdateChannels.c"
#include "game/HOWL/h81_Cutscene_VolumeBackup.c"
#include "game/HOWL/h82_Cutscene_VolumeRestore.c"
#include "game/HOWL/h83_howl_PlayAudio_Update.c"
#include "game/HOWL/h84_howl_InitChannelAttr_EngineFX.c"
#include "game/HOWL/h85_howl_InitChannelAttr_OtherFX.c"
#include "game/HOWL/h86_howl_PauseAudio.c"
#include "game/HOWL/h87_howl_UnPauseChannel.c"
#include "game/HOWL/h88_howl_UnPauseAudio.c"
#include "game/HOWL/h89_howl_StopAudio.c"
#include "game/HOWL/h90_Voiceline_PoolInit.c"
#include "game/HOWL/h91_Voiceline_ClearTimeStamp.c"
#include "game/HOWL/h92_Voiceline_PoolClear.c"
#include "game/HOWL/h93_Voiceline_StopAll.c"
#include "game/HOWL/h94_Voiceline_ToggleEnable.c"
#include "game/HOWL/h99_Voiceline_SetDefaults.c"
#include "game/HOWL/h100_Audio_SetState.c"
#include "game/HOWL/h101_Audio_SetState_Safe.c"
#include "game/HOWL/h102_Audio_AdvHub_SwapSong.c"
#include "game/HOWL/h103_Audio_SetMaskSong.c"
#include "game/HOWL/h104_Audio_Update1.c"
#include "game/HOWL/h105_Audio_SetDefaults.c"
#include "game/HOWL/h106_Audio_SetReverbMode.c"
#include "game/HOWL/h107_Music_SetIntro.c"
#include "game/HOWL/h108_Music_LoadBanks.c"
#include "game/HOWL/h109_Music_AsyncParseBanks.c"
#include "game/HOWL/h110_Music_SetDefaults.c"
#include "game/HOWL/h111_Music_Adjust.c"
#include "game/HOWL/h112_Music_LowerVolume.c"
#include "game/HOWL/h113_Music_RaiseVolume.c"
#include "game/HOWL/h114_Music_Restart.c"
#include "game/HOWL/h115_Music_Stop.c"
#include "game/HOWL/h116_Music_Start.c"
#include "game/HOWL/h117_Music_End.c"
#include "game/HOWL/h118_Music_GetHighestSongPlayIndex.c"
#include "game/HOWL/h140_Garage_PlayFX.c"

#include "game/INSTANCE/INSTANCE_00_Birth.c"
#include "game/INSTANCE/INSTANCE_01_Birth3D.c"
#include "game/INSTANCE/INSTANCE_02_Birth2D.c"
#include "game/INSTANCE/INSTANCE_03_BirthWithThread.c"
#include "game/INSTANCE/INSTANCE_04_BirthWithThread_Stack.c"
#include "game/INSTANCE/INSTANCE_05_Death.c"
#include "game/INSTANCE/INSTANCE_06_LevInitAll.c"
#include "game/INSTANCE/INSTANCE_08_GetNumAnimFrames.c"

#include "game/JitPool/JitPool_0_Clear.c"
#include "game/JitPool/JitPool_1_Init.c"
#include "game/JitPool/JitPool_2_Add.c"
#include "game/JitPool/JitPool_3_Remove.c"

#include "game/LevInstDef/LevInstDef_0_UnPack.c"
#include "game/LevInstDef/LevInstDef_1_RePack.c"

#include "game/LibraryOfModels/LibraryOfModels_1_Clear.c"

#include "game/LinkedCollide/LinkedCollide_2_Hitbox.c"

#include "game/LIST/LIST_0_Clear.c"
#include "game/LIST/LIST_1_AddFront.c"
#include "game/LIST/LIST_2_AddBack.c"
#include "game/LIST/LIST_3_GetNextItem.c"
#include "game/LIST/LIST_4_GetFirstItem.c"
#include "game/LIST/LIST_5_RemoveMember.c"
#include "game/LIST/LIST_6_RemoveFront.c"
#include "game/LIST/LIST_7_RemoveBack.c"
#include "game/LIST/LIST_8_Init.c"

#include "game/LOAD/LOAD_00_50_FULL.c"

#include "game/MAIN/MainDB_00_GetClipSize.c"
#include "game/MAIN/MainDB_01_PrimMem.c"
#include "game/MAIN/MainDB_02_OTMem.c"
#include "game/MAIN/MainDrawCb_00_DrawSync.c"
#include "game/MAIN/MainDrawCb_01_Vsync.c"

#include "game/MAIN/MainFrame_00_TogglePauseAudio.c"
#include "game/MAIN/MainFrame_01_ResetDB.c"
#include "game/MAIN/MainFrame_02_GameLogic.c"
#include "game/MAIN/MainFrame_07_RequestMaskHint.c"
#include "game/MAIN/MainFrame_08_RenderFrame.c"

#include "game/MAIN/MainFreeze_04_MenuPtrQuit.c"
#include "game/MAIN/MainFreeze_05_SafeAdvDestroy.c"
#include "game/MAIN/MainFreeze_06_MenuPtrDefault.c"
#include "game/MAIN/MainFreeze_07_GetMenuPtr.c"
#include "game/MAIN/MainFreeze_08_IfPressStart.c"

#include "game/MAIN/MainGameStart_00_Initialize.c"

#include "game/MAIN/MainRaceTrack_00_StartLoad.c"
#include "game/MAIN/MainRaceTrack_01_RequestLoad.c"

#include "game/MATH/MATH_1_Cos.c"
#include "game/MATH/MATH_MatrixRotate.c"

#include "game/MEMCARD/MEMCARD_06_InitCard.c"

#include "game/MEMPACK/MEMPACK_00_Init.c"
#include "game/MEMPACK/MEMPACK_01_SwapPacks.c"
#include "game/MEMPACK/MEMPACK_02_NewPack.c"
#include "game/MEMPACK/MEMPACK_03_GetFreeBytes.c"
#include "game/MEMPACK/MEMPACK_04_AllocMem.c"
#include "game/MEMPACK/MEMPACK_05_AllocHighMem.c"
#include "game/MEMPACK/MEMPACK_06_ClearHighMem.c"
#include "game/MEMPACK/MEMPACK_07_ReallocMem.c"
#include "game/MEMPACK/MEMPACK_08_PushState.c"
#include "game/MEMPACK/MEMPACK_09_ClearLowMem.c"
#include "game/MEMPACK/MEMPACK_10_PopState.c"
#include "game/MEMPACK/MEMPACK_11_PopToState.c"

#include "game/MixRNG/MixRNG_0_Scramble.c"

#include "game/PROC/PROC_00_DestroyTracker.c"
#include "game/PROC/PROC_01_DestroyInstance.c"
#include "game/PROC/PROC_02_DestroyObject.c"
#include "game/PROC/PROC_03_DestroySelf.c"
#include "game/PROC/PROC_04_DestroyBloodline.c"
#include "game/PROC/PROC_05_CheckBloodlineForDead.c"
#include "game/PROC/PROC_06_CheckAllForDead.c"
#include "game/PROC/PROC_07_BirthWithObject.c"
#include "game/PROC/PROC_08_CollidePointWithSelf.c"
#include "game/PROC/PROC_09_CollidePointWithBucket.c"
#include "game/PROC/PROC_10_SearchForModel.c"

#include "game/PushBuffer/PushBuffer_00_Init.c"
#include "game/PushBuffer/PushBuffer_01_SetPsyqGeom.c"
#include "game/PushBuffer/PushBuffer_03_SetDrawEnv_Normal.c"
#include "game/PushBuffer/PushBuffer_04_SetMatrixVP.c"
#include "game/PushBuffer/PushBuffer_07_FadeOneWindow.c"
#include "game/PushBuffer/PushBuffer_08_FadeAllWindows.c"

#include "game/QueueLoadTrack/QueueLoadTrack_0_MenuProc.c"
#include "game/QueueLoadTrack/QueueLoadTrack_1_GetMenuPtr.c"

#include "game/RaceFlag/RaceFlag_00_MoveModels.c"
#include "game/RaceFlag/RaceFlag_01_IsFullyOnScreen.c"
#include "game/RaceFlag/RaceFlag_02_IsFullyOffScreen.c"
#include "game/RaceFlag/RaceFlag_03_IsTransitioning.c"
#include "game/RaceFlag/RaceFlag_04_SetDrawOrder.c"
#include "game/RaceFlag/RaceFlag_05_BeginTransition.c"
#include "game/RaceFlag/RaceFlag_06_SetFullyOnScreen.c"
#include "game/RaceFlag/RaceFlag_07_SetFullyOffScreen.c"
#include "game/RaceFlag/RaceFlag_08_SetCanDraw.c"
#include "game/RaceFlag/RaceFlag_09_GetCanDraw.c"
#include "game/RaceFlag/RaceFlag_10_GetOT.c"
#include "game/RaceFlag/RaceFlag_11_ResetTextAnim.c"
#include "game/RaceFlag/RaceFlag_12_DrawLoadingString.c"
#include "game/RaceFlag/RaceFlag_13_DrawSelf.c"

#include "game/RECTMENU/RECTMENU_00_DrawPolyGT4.c"
#include "game/RECTMENU/RECTMENU_01_DrawOuterRect_Edge.c"
#include "game/RECTMENU/RECTMENU_02_DrawTime.c"
#include "game/RECTMENU/RECTMENU_03_DrawRwdBlueRect_Subset.c"
#include "game/RECTMENU/RECTMENU_04_DrawRwdBlueRect.c"
#include "game/RECTMENU/RECTMENU_05_DrawRwdTriangle.c"
#include "game/RECTMENU/RECTMENU_06_DrawOuterRect_LowLevel.c"
#include "game/RECTMENU/RECTMENU_07_DrawOuterRect_HighLevel.c"
#include "game/RECTMENU/RECTMENU_08_DrawQuip.c"
#include "game/RECTMENU/RECTMENU_09_DrawInnerRect.c"
#include "game/RECTMENU/RECTMENU_10_DrawFullRect.c"
#include "game/RECTMENU/RECTMENU_11_GetHeight.c"
#include "game/RECTMENU/RECTMENU_12_GetWidth.c"
#include "game/RECTMENU/RECTMENU_13_DrawSelf.c"
#include "game/RECTMENU/RECTMENU_14_ClearInput.c"
#include "game/RECTMENU/RECTMENU_15_CollectInput.c"
#include "game/RECTMENU/RECTMENU_16_ProcessInput.c"
#include "game/RECTMENU/RECTMENU_17_ProcessState.c"
#include "game/RECTMENU/RECTMENU_18_Show.c"
#include "game/RECTMENU/RECTMENU_19_Hide.c"
#include "game/RECTMENU/RECTMENU_20_BoolHidden.c"

#include "game/SubmitName/SubmitName_0_RestoreName.c"
#include "game/SubmitName/SubmitName_1_DrawMenu.c"
#include "game/SubmitName/SubmitName_2_MenuProc.c"

#include "game/Timer/Timer_0_Init.c"
#include "game/Timer/Timer_1_Destroy.c"
#include "game/Timer/Timer_2_GetTime_Total.c"
#include "game/Timer/Timer_3_GetTime_Elapsed.c"

#include "game/prim.c"
#include "game/math.c"
#include "game/gte.c"
#include "game/UI/UI_00_SaveLapTime.c"
#include "game/UI/UI_01_ThTick_CountPickup.c"
#include "game/UI/UI_02_ThTick_Reward.c"
#include "game/UI/UI_03_ThTick_CtrLetters.c"
#include "game/UI/UI_04_ThTick_big1.c"
#include "game/UI/UI_05_ConvertX_2.c"
#include "game/UI/UI_06_ConvertY_2.c"
#include "game/UI/UI_07_INSTANCE_BirthWithThread.c"
#include "game/UI/UI_08_INSTANCE_InitAll.c"
#include "game/UI/UI_09_Map_DrawMap.c"
#include "game/UI/UI_10_Map_GetIconPos.c"
#include "game/UI/UI_11_Map_DrawAdvPlayer.c"
#include "game/UI/UI_12_Map_DrawRawIcon.c"
#include "game/UI/UI_13_Map_DrawDrivers.c"
#include "game/UI/UI_14_Map_DrawGhosts.c"
#include "game/UI/UI_15_Map_DrawTracking.c"
#include "game/UI/UI_16_WeaponBG_AnimateShine.c"
#include "game/UI/UI_17_WeaponBG_DrawShine.c"
#include "game/UI/UI_18_TrackerBG.c"
#include "game/UI/UI_19_DrawDriverIcon.c"
#include "game/UI/UI_20_Lerp2D_Angular.c"
#include "game/UI/UI_21_Lerp2D_HUD.c"
#include "game/UI/UI_22_Lerp2D_Linear.c"
#include "game/UI/UI_23_DrawRaceClock.c"
#include "game/UI/UI_24_DrawLimitClock.c"
#include "game/UI/UI_25_BattleDrawHeadArrows.c"
#include "game/UI/UI_26_TrackerSelf.c"
#include "game/UI/UI_27_DrawPosSuffix.c"
#include "game/UI/UI_28_DrawLapCount.c"
#include "game/UI/UI_29_DrawBattleScores.c"
#include "game/UI/UI_30_Weapon_DrawSelf.c"
#include "game/UI/UI_31_Weapon_DrawBG.c"
#include "game/UI/UI_32_DrawNumWumpa.c"
#include "game/UI/UI_33_DrawNumTimebox.c"
#include "game/UI/UI_34_DrawNumRelic.c"
#include "game/UI/UI_35_DrawNumKey.c"
#include "game/UI/UI_36_DrawNumTrophy.c"
#include "game/UI/UI_37_DrawNumCrystal.c"
#include "game/UI/UI_38_DrawSpeedNeedle.c"
#include "game/UI/UI_39_DrawSpeedBG.c"
#include "game/UI/UI_40_JumpMeter_Update.c"
#include "game/UI/UI_41_JumpMeter_Draw.c"
#include "game/UI/UI_42_DrawSlideMeter.c"
#include "game/UI/UI_43_DrawRankedDrivers.c"
#include "game/UI/UI_44_RenderFrame_Racing.c"
#include "game/UI/UI_45_RenderFrame_AdvHub.c"
#include "game/UI/UI_46_RenderFrame_CrystChall.c"
#include "game/UI/UI_53_RaceEnd_GetDriverClock.c"

#include "game/Vehicle/VehBirth_0_TeleportSelf.c"
#include "game/Vehicle/VehBirth_1_TeleportAll.c"
#include "game/Vehicle/VehBirth_3_SetConsts.c"
#include "game/Vehicle/VehBirth_4_EngineAudio_AllPlayers.c"
#include "game/Vehicle/VehBirth_5_NullThread.c"
#include "game/Vehicle/VehBirth_6_TireSprites.c"
#include "game/Vehicle/VehBirth_7_NonGhost.c"
#include "game/Vehicle/VehBirth_8_Player.c"

#include "game/Vehicle/VehCalc_0_InterpBySpeed.c"
#include "game/Vehicle/VehCalc_1_MapToRange.c"
#include "game/Vehicle/VehCalc_2_SteerAccel.c"

#include "game/Vehicle/VehFire_0_Audio.c"
#include "game/Vehicle/VehFire_1_Increment.c"

#include "game/Vehicle/VehFrameInst_1_GetNumAnimFrames.c"

#include "game/Vehicle/VehPhysForce_0_ConvertSpeedToVec.c"
#include "game/Vehicle/VehPhysForce_2_OnApplyForces.c"

#include "game/Vehicle/VehPhysGeneral_0_PhysAngular.c"
#include "game/Vehicle/VehPhysGeneral_1_LerpQuarterStrength.c"
#include "game/Vehicle/VehPhysGeneral_2_LerpToForwards.c"
#include "game/Vehicle/VehPhysGeneral_5_SetHeldItem.c"
#include "game/Vehicle/VehPhysGeneral_6_GetBaseSpeed.c"

#include "game/Vehicle/VehPhysJoystick_0_ReturnToRest.c"
#include "game/Vehicle/VehPhysJoystick_1_GetStrength.c"
#include "game/Vehicle/VehPhysJoystick_2_GetStrengthAbsolute.c"

#include "game/Vehicle/VehPhysProc_00_Driving_PhysLinear.c"
#include "game/Vehicle/VehPhysProc_01_Driving_Audio.c"
#include "game/Vehicle/VehPhysProc_02_Driving_Update.c"
#include "game/Vehicle/VehPhysProc_03_Driving_Init.c"
#include "game/Vehicle/VehPhysProc_04_FreezeEndEvent_PhysLinear.c"
#include "game/Vehicle/VehPhysProc_05_FreezeEndEvent_Init.c"

#include "game/Vehicle/VehPhysProc_AAA_BigBlock1.c"

#include "game/Vehicle/VehPickupItem_0_MaskBoolGoodGuy.c"
#include "game/Vehicle/VehPickupItem_4_ShootNow.c"
#include "game/Vehicle/VehPickupItem_5_ShootOnCirclePress.c"

#include "game/Vehicle/VehStuckProc_11_RevEngine_Update.c"
#include "game/Vehicle/VehStuckProc_12_RevEngine_PhysLinear.c"
#include "game/Vehicle/VehStuckProc_13_RevEngine_Animate.c"
#include "game/Vehicle/VehStuckProc_14_RevEngine_Init.c"
#include "game/Vehicle/VehStuckProc_15_Tumble_Update.c"
#include "game/Vehicle/VehStuckProc_16_Tumble_PhysLinear.c"
#include "game/Vehicle/VehStuckProc_17_Tumble_PhysAngular.c"
#include "game/Vehicle/VehStuckProc_18_Tumble_Animate.c"
#include "game/Vehicle/VehStuckProc_19_Tumble_Init.c"

#include "game/Vehicle/VehTalkMask_0_ThTick.c"
#include "game/Vehicle/VehTalkMask_1_Init.c"
#include "game/Vehicle/VehTalkMask_2_PlayXA.c"
#include "game/Vehicle/VehTalkMask_3_boolNoXA.c"
#include "game/Vehicle/VehTalkMask_4_End.c"

#include "game/230/R230.c"
#include "game/230/D230.c"

#include "game/230/230_00_38_MM_Battle_DrawIcon_Character.c"
#include "game/230/230_39_MM_AdvNewLoad_GetMenuPtr.c"
#include "game/230/230_40_54_MM_Characters_AnimateColors.c"
#include "game/230/230_55_MM_TrackSelect_Init.c"
#include "game/230/230_56_MM_TrackSelect_MenuProc.c"
#include "game/230/230_57_MM_TrackSelect_GetMenuPtr.c"
#include "game/230/230_58_76_MM_CupSelect_Init.c"

#include "game/231/D231.c"

#include "game/231/231_002_RB_Player_ModifyWumpa.c"
#include "game/231/231_003_RB_MinePool_Init.c"
#include "game/231/231_004_RB_MinePool_Remove.c"
#include "game/231/231_005_RB_MinePool_Add.c"
#include "game/231/231_006_RB_Hazard_HurtDriver.c"
#include "game/231/231_007_RB_Hazard_CollideWithDrivers.c"
#include "game/231/231_008_RB_Hazard_CollideWithBucket.c"
#include "game/231/231_009_RB_Hazard_ThCollide_Generic_Alt.c"
#include "game/231/231_010_RB_Hazard_ThCollide_Missile.c"
#include "game/231/231_011_RB_Hazard_ThCollide_Generic.c"

#include "game/231/231_023_RB_Hazard_InterpolateValue.c"
#include "game/231/231_024_RB_MovingExplosive_ThTick.c"
#include "game/231/231_025_RB_MovingExplosive_Explode.c"

#include "game/231/231_055_RB_GetThread_ClosestTracker.c"
#include "game/231/231_056_072_RB_Baron_ThTick.c"

#include "game/231/231_082_085_RB_Armadillo.c"
#include "game/231/231_086_088_RB_Fireball.c"
#include "game/231/231_095_098_RB_Fruit.c"
#include "game/231/231_099_100_RB_Minecart.c"
#include "game/231/231_104_109_RB_Plant.c"
#include "game/231/231_110_113_RB_Seal.c"
#include "game/231/231_114_115_RB_Snowball.c"
#include "game/231/231_116_119_RB_Spider.c"
#include "game/231/231_127_129_RB_Turtle.c"

#include "game/232/R232.c"
#include "game/232/D232.c"

#include "game/232/232_Full.c"

#include "game/233/233_09_CS_Instance_GetFrameData.c"
#include "game/233/233_02_09_CS_ScriptCmd.c"
#include "game/233/233_10_CS_Instance_GetNumAnimFrames.c"
#include "game/233/233_11_CS_Instance_SafeCheckAnimFrame.c"
#include "game/233/233_12_CS_Instance_BoolPlaySound.c"
#include "game/233/233_13_CS_DestroyPodium_StartDriving.c"
#include "game/233/233_14_CS_Thread_UseOpcode.c"
#include "game/233/233_15_CS_Thread_AnimateScale.c"
#include "game/233/233_01_CS_Thread_LInB.c"
#include "game/233/233_stubs.c"
#include "game/233/233_24_CS_Thread_Init.c"
#include "game/233/233_25_CS_Instance_InitMatrix.c"
#include "game/233/233_29_CS_Podium_Prize_ThDestroy.c"
#include "game/233/233_35_CS_Cutscene_Start.c"
#include "game/233/233_44_CS_Credits_GetNextString.c"
#include "game/233/233_45_CS_Credits_DestroyCreditGhost.c"
#include "game/233/233_46_CS_Credits_AnimateCreditGhost.c"
#include "game/233/233_47_CS_Credits_Init.c"
#include "game/233/233_48_CS_Credits_IsTextValid.c"
#include "game/233/233_49_CS_Credits_NewDancer.c"
#include "game/233/233_51_CS_Credits_End.c"
#include "game/233/233_52_CS_Credits_DrawNames.c"
#include "game/233/233_53_CS_Credits_DrawEpilogue.c"
#include "game/233/233_54_CS_Credits_ThTick.c"
#include "game/233/233_50_CS_Credits_NewCreditGhosts.c"
#include "game/233/233_37_40_CS_Garage.c"
#include "game/233/D233.c"
#include "game/233/233_zGlobal_gGarage.c"

#endif
