#ifndef GAME_INCLUDES_H
#define GAME_INCLUDES_H

#include <common.h>

#include "game/226/R226.c"
#include "game/227/R227.c"
#include "game/228/R228.c"
#include "game/229/R229.c"
#include "game/226/226_00_DrawLevelOvr1P.c"
#include "game/227/227_00_DrawLevelOvr2P.c"
#include "game/228/228_00_DrawLevelOvr3P.c"
#include "game/229/229_00_DrawLevelOvr4P.c"
#include "game/DrawConfetti/DrawConfetti.c"
#include "game/DrawSky/DrawSky.c"

#include "game/RenderBucket/RenderBucket_08_InitDepthGTE.c"
#include "game/RenderBucket/RenderBucket_QueueExecute.c"
#include "game/RenderLevel/AnimateWater.c"
#include "game/RenderLevel/RenderLists.c"
#include "game/RenderTires/DrawTires_Solid.c"
#include "game/RenderTires/DrawTires_Reflection.c"
#include "game/RenderStars/RenderStars.c"
#include "game/Torch/Torch.c"
#include "game/RenderWeather/RedBeaker_RenderRain.c"
#include "game/RenderWeather/RenderWeather.c"

#include "game/MAIN/MAIN_AAA_BigBlock1.c"

#include "game/CAM.c"

#include "game/BOTS.c"
#include "game/CDSYS.c"

#include "game/COLL/COLL_00_LevModelMeta.c"
#include "game/COLL/COLL_01_SearchBSP_CallbackQUADBLK.c"
#include "game/COLL/COLL_06_SearchBSP_CallbackPARAM.c"
#include "game/COLL/COLL_07_FIXED_TRIANGL_Barycentrics.c"
#include "game/COLL/COLL_01_FIXED_INSTANC_TestPoint.c"
#include "game/COLL/COLL_02_FIXED_BSPLEAF_TestInstance.c"
#include "game/COLL/COLL_03_FIXED_BotsSearch.c"
#include "game/COLL/COLL_08_FIXED_TRIANGL_UNUSED.c"
#include "game/COLL/COLL_09_FIXED_TRIANGL_TestPoint.c"
#include "game/COLL/COLL_10_FIXED_TRIANGL_GetNormVec.c"
#include "game/COLL/COLL_15_FIXED_QUADBLK_LoadScratchpadVerts.c"
#include "game/COLL/COLL_13_FIXED_QUADBLK_GetNormVecs_LoLOD.c"
#include "game/COLL/COLL_14_FIXED_QUADBLK_GetNormVecs_HiLOD.c"
#include "game/COLL/COLL_11_FIXED_QUADBLK_TestTriangles.c"
#include "game/COLL/COLL_12_FIXED_BSPLEAF_TestQuadblocks.c"
#include "game/COLL/COLL_04_FIXED_PlayerSearch.c"
#include "game/COLL/COLL_16_MOVED_TRIANGL_ReorderNormals.c"
#include "game/COLL/COLL_17_MOVED_TRIANGL_TestPoint.c"
#include "game/COLL/COLL_18_MOVED_QUADBLK_TestTriangles.c"
#include "game/COLL/COLL_19_MOVED_BSPLEAF_TestQuadblocks.c"
#include "game/COLL/COLL_20_MOVED_FindScrub.c"
#include "game/COLL/COLL_21_MOVED_PlayerSearch.c"
#include "game/COLL/COLL_22_MOVED_ScrubImpact.c"

#include "game/CTR/CTR_00_Box_DrawWirePrims.c"
#include "game/CTR/CTR_01_Box_DrawWireBox.c"
#include "game/CTR/CTR_02_Box_DrawClearBox.c"
#include "game/CTR/CTR_03_Box_DrawSolidBox.c"
#include "game/CTR/CTR_04_CycleTex_LEV.c"
#include "game/CTR/CTR_05_CycleTex_Model.c"
#include "game/CTR/CTR_06_CycleTex_AllModels.c"
#include "game/CTR/CTR_07_CycleTex_2p3p4pWumpaHUD.c"
#include "game/CTR/CTR_08_ClearRenderLists_1P2P.c"
#include "game/CTR/CTR_09_ClearRenderLists_3P4P.c"
#include "game/CTR/CTR_10_EmptyFunc_MainFrame_ResetDB.c"
#include "game/CTR/CTR_11_ErrorScreen.c"
#include "game/CTR/CTR_12_unknownMaybeThunk1.c"
#include "game/CTR/CTR_14_unknownMaybeThunk2.c"
#include "game/CTR/CTR_16_unknownMaybeThunk3.c"
#include "game/CTR/CTR_17_MatrixToRot.c"
#include "game/CTR/CTR_18_ScrambleGhostString.c"

#include "game/DebugFont.c"

#include "game/DecalFont.c"

#include "game/DecalGlobal.c"

#include "game/DecalHUD.c"

#include "game/DecalMP.c"

#include "game/Display.c"

#include "game/DotLights.c"

#include "game/DropRain.c"

#include "game/ElimBG.c"

#include "game/FLARE.c"

#include "game/GAMEPAD.c"

#include "game/GAMEPROG.c"

#include "game/GhostReplay.c"

#include "game/GhostTape.c"

#include "game/HOWL/h01_CountSounds.c"
#include "game/HOWL/h02_OtherFX_Play.c"
#include "game/HOWL/h03_OtherFX_Play_Echo.c"
#include "game/HOWL/h04_OtherFX_Play_LowLevel.c"
#include "game/HOWL/h05_OtherFX_Modify.c"
#include "game/HOWL/h06_OtherFX_Stop1.c"
#include "game/HOWL/h07_OtherFX_Stop2.c"
#include "game/HOWL/h119_GTE_AudioLR_Inst.c"
#include "game/HOWL/h120_GTE_AudioLR_Driver.c"
#include "game/HOWL/h121_GTE_GetSquaredLength.c"
#include "game/HOWL/h122_OtherFX_RecycleNew.c"
#include "game/HOWL/h123_OtherFX_RecycleMute.c"
#include "game/HOWL/h124_OtherFX_DriverCrashing.c"
#include "game/HOWL/h125_GTE_GetSquaredDistance.c"
#include "game/HOWL/h126_CalculateVolumeFromDistance.c"
#include "game/HOWL/h127_PlayWarppadSound.c"
#include "game/HOWL/h128_Level_SoundLoopSet.c"
#include "game/HOWL/h129_Level_SoundLoopFade.c"
#include "game/HOWL/h130_Level_RandomFX.c"
#include "game/HOWL/h131_Level_AmbientSound.c"
#include "game/HOWL/h132_PlaySound3D.c"
#include "game/HOWL/h133_PlaySound3D_Flags.c"
#include "game/HOWL/h08_EngineAudio_InitOnce.c"
#include "game/HOWL/h09_EngineAudio_Recalculate.c"
#include "game/HOWL/h134_EngineSound_Player.c"
#include "game/HOWL/h135_EngineSound_VolumeAdjust.c"
#include "game/HOWL/h136_EngineSound_AI.c"
#include "game/HOWL/h137_EngineSound_NearestAIs.c"
#include "game/HOWL/h10_EngineAudio_Stop.c"
#include "game/HOWL/h11_SetReverbMode.c"
#include "game/HOWL/h12_CseqMusic_Start.c"
#include "game/HOWL/h13_CseqMusic_Pause.c"
#include "game/HOWL/h14_CseqMusic_Resume.c"
#include "game/HOWL/h15_CseqMusic_ChangeVolume.c"
#include "game/HOWL/h16_CseqMusic_Restart.c"
#include "game/HOWL/h17_CseqMusic_ChangeTempo.c"
#include "game/HOWL/h18_CseqMusic_AdvHubSwap.c"
#include "game/HOWL/h19_CseqMusic_Stop.c"
#include "game/HOWL/h20_CseqMusic_StopAll.c"
#include "game/HOWL/h21_Bank_ResetAllocator.c"
#include "game/HOWL/h22_Bank_Alloc.c"
#include "game/HOWL/h23_Bank_AssignSpuAddrs.c"
#include "game/HOWL/h24_Bank_Destroy.c"
#include "game/HOWL/h25_Bank_ClearInRange.c"
#include "game/HOWL/h26_Bank_Load.c"
#include "game/HOWL/h27_Bank_DestroyLast.c"
#include "game/HOWL/h28_Bank_DestroyUntilIndex.c"
#include "game/HOWL/h29_Bank_DestroyAll.c"
#include "game/HOWL/h30_howl_InstrumentPitch.c"
#include "game/HOWL/h31_howl_InitGlobals.c"
#include "game/HOWL/h32_howl_ParseHeader.c"
#include "game/HOWL/h33_howl_ParseCseqHeader.c"
#include "game/HOWL/h34_howl_LoadHeader.c"
#include "game/HOWL/h35_howl_SetSong.c"
#include "game/HOWL/h36_howl_LoadSong.c"
#include "game/HOWL/h37_howl_ErasePtrCseqHeader.c"
#include "game/HOWL/h38_howl_GetNextNote.c"
#include "game/HOWL/h39_cseq_opcode01_noteoff.c"
#include "game/HOWL/h40_cseq_opcode03.c"
#include "game/HOWL/h41_howl_InitChannelAttr_Music.c"
#include "game/HOWL/h42_cseq_opcode_from06and07.c"
#include "game/HOWL/h43_cseq_opcode05_noteon.c"
#include "game/HOWL/h44_cseq_opcode06.c"
#include "game/HOWL/h45_cseq_opcode07.c"
#include "game/HOWL/h46_cseq_opcode08.c"
#include "game/HOWL/h47_cseq_opcode09.c"
#include "game/HOWL/h48_cseq_opcode0a.c"
#include "game/HOWL/h49_SongPool_FindFreeChannel.c"
#include "game/HOWL/h50_SongPool_CalculateTempo.c"
#include "game/HOWL/h51_SongPool_ChangeTempo.c"
#include "game/HOWL/h52_SongPool_Start.c"
#include "game/HOWL/h53_SongPool_Volume.c"
#include "game/HOWL/h54_SongPool_AdvHub1.c"
#include "game/HOWL/h55_SongPool_AdvHub2.c"
#include "game/HOWL/h56_SongPool_StopCseq.c"
#include "game/HOWL/h57_SongPool_StopAllCseq.c"
#include "game/HOWL/h58_howl_Disable.c"
#include "game/HOWL/h59_UpdateChannelVol_EngineFX.c"
#include "game/HOWL/h60_UpdateChannelVol_OtherFX.c"
#include "game/HOWL/h61_UpdateChannelVol_Music.c"
#include "game/HOWL/h62_UpdateChannelVol_EngineFX_All.c"
#include "game/HOWL/h63_UpdateChannelVol_Music_All.c"
#include "game/HOWL/h64_UpdateChannelVol_OtherFX_All.c"
#include "game/HOWL/h65_howl_VolumeGet.c"
#include "game/HOWL/h66_howl_VolumeSet.c"
#include "game/HOWL/h67_howl_ModeGet.c"
#include "game/HOWL/h68_howl_ModeSet.c"
#include "game/HOWL/h69_OptionsMenu_TestSound.c"
#include "game/HOWL/h70_Smart_EnterCriticalSection.c"
#include "game/HOWL/h71_Smart_ExitCriticalSection.c"
#include "game/HOWL/h72_Channel_SetVolume.c"
#include "game/HOWL/h73_Channel_FindSound.c"
#include "game/HOWL/h74_Channel_AllocSlot_AntiSpam.c"
#include "game/HOWL/h75_Channel_AllocSlot.c"
#include "game/HOWL/h76_Channel_SearchFX_EditAttr.c"
#include "game/HOWL/h77_Channel_SearchFX_Destroy.c"
#include "game/HOWL/h78_Channel_DestroyAll_LowLevel.c"
#include "game/HOWL/h79_Channel_ParseSongToChannels.c"
#include "game/HOWL/h80_Channel_UpdateChannels.c"
#include "game/HOWL/h81_Cutscene_VolumeBackup.c"
#include "game/HOWL/h82_Cutscene_VolumeRestore.c"
#include "game/HOWL/h83_howl_PlayAudio_Update.c"
#include "game/HOWL/h84_howl_InitChannelAttr_EngineFX.c"
#include "game/HOWL/h85_howl_InitChannelAttr_OtherFX.c"
#include "game/HOWL/h86_howl_PauseAudio.c"
#include "game/HOWL/h87_howl_UnPauseChannel.c"
#include "game/HOWL/h88_howl_UnPauseAudio.c"
#include "game/HOWL/h89_howl_StopAudio.c"
#include "game/HOWL/h90_Voiceline_PoolInit.c"
#include "game/HOWL/h91_Voiceline_ClearTimeStamp.c"
#include "game/HOWL/h92_Voiceline_PoolClear.c"
#include "game/HOWL/h93_Voiceline_StopAll.c"
#include "game/HOWL/h94_Voiceline_ToggleEnable.c"
#include "game/HOWL/h95_Voiceline_RequestPlay.c"
#include "game/HOWL/h96_Voiceline_StartPlay.c"
#include "game/HOWL/h97_Voiceline_Update.c"
#include "game/HOWL/h98_Voiceline_EmptyFunc.c"
#include "game/HOWL/h99_Voiceline_SetDefaults.c"
#include "game/HOWL/h100_Audio_SetState.c"
#include "game/HOWL/h101_Audio_SetState_Safe.c"
#include "game/HOWL/h102_Audio_AdvHub_SwapSong.c"
#include "game/HOWL/h103_Audio_SetMaskSong.c"
#include "game/HOWL/h104_Audio_Update1.c"
#include "game/HOWL/h105_Audio_SetDefaults.c"
#include "game/HOWL/h106_Audio_SetReverbMode.c"
#include "game/HOWL/h107_Music_SetIntro.c"
#include "game/HOWL/h108_Music_LoadBanks.c"
#include "game/HOWL/h109_Music_AsyncParseBanks.c"
#include "game/HOWL/h110_Music_SetDefaults.c"
#include "game/HOWL/h111_Music_Adjust.c"
#include "game/HOWL/h112_Music_LowerVolume.c"
#include "game/HOWL/h113_Music_RaiseVolume.c"
#include "game/HOWL/h114_Music_Restart.c"
#include "game/HOWL/h115_Music_Stop.c"
#include "game/HOWL/h116_Music_Start.c"
#include "game/HOWL/h117_Music_End.c"
#include "game/HOWL/h118_Music_GetHighestSongPlayIndex.c"
#include "game/HOWL/h138_Garage_Init.c"
#include "game/HOWL/h139_Garage_Enter.c"
#include "game/HOWL/h140_Garage_PlayFX.c"
#include "game/HOWL/h141_Garage_LerpFX.c"
#include "game/HOWL/h142_Garage_MoveLR.c"
#include "game/HOWL/h143_Garage_Leave.c"

#include "game/INSTANCE.c"

#include "game/LHMatrix.c"

#include "game/JitPool.c"

#include "game/LevInstDef.c"

#include "game/LibraryOfModels/LibraryOfModels_1_Clear.c"

#include "game/LinkedCollide.c"

#include "game/LIST.c"

#include "game/LOAD/LOAD_00_50_FULL.c"

#include "game/MAIN/MainDB_00_GetClipSize.c"
#include "game/MAIN/MainDB_01_PrimMem.c"
#include "game/MAIN/MainDB_02_OTMem.c"
#include "game/MAIN/MainDrawCb_00_DrawSync.c"
#include "game/MAIN/MainDrawCb_01_Vsync.c"

#include "game/MAIN/MainFrame_00_TogglePauseAudio.c"
#include "game/MAIN/MainFrame_01_ResetDB.c"
#include "game/MAIN/MainFrame_02_GameLogic.c"
#include "game/MAIN/MainFrame_05_InitVideoSTR.c"
#include "game/MAIN/MainFrame_06_HaveAllPads.c"
#include "game/MAIN/MainFrame_07_VisMemFullFrame.c"
#include "game/MAIN/MainFrame_07_RequestMaskHint.c"
#include "game/MAIN/MainFrame_08_RenderFrame.c"

#include "game/MAIN/MainFreeze_00_ConfigDrawNPC105.c"
#include "game/MAIN/MainFreeze_01_ConfigDrawArrows.c"
#include "game/MAIN/MainFreeze_02_ConfigSetupEntry.c"
#include "game/MAIN/MainFreeze_03_MenuPtrOptions.c"
#include "game/MAIN/MainFreeze_04_MenuPtrQuit.c"
#include "game/MAIN/MainFreeze_05_SafeAdvDestroy.c"
#include "game/MAIN/MainFreeze_06_MenuPtrDefault.c"
#include "game/MAIN/MainFreeze_07_GetMenuPtr.c"
#include "game/MAIN/MainFreeze_08_IfPressStart.c"

#include "game/MAIN/MainGameStart_00_Initialize.c"
#include "game/MAIN/MainGameEnd_00_SoloRaceGetReward.c"
#include "game/MAIN/MainGameEnd_01_SoloRaceSaveHighScore.c"
#include "game/MAIN/MainGameEnd_02_Initialize.c"
#include "game/MAIN/MainStats_00_ClearBattleVS.c"
#include "game/MAIN/MainStats_01_RestartRaceCountLoss.c"

#include "game/MAIN/MainRaceTrack_00_StartLoad.c"
#include "game/MAIN/MainRaceTrack_01_RequestLoad.c"

#include "game/MATH/MATH_1_Cos.c"
#include "game/MATH/TRIG_AngleSinCos.c"
#include "game/MATH/MATH_2_FastSqrt.c"
#include "game/MATH/MATH_3_HitboxMatrix.c"
#include "game/MATH/MATH_7_MatrixStubs.c"
#include "game/MATH/MATH_MatrixRotate.c"
#include "game/MATH/MATH_6_MatrixMul.c"

#include "game/MEMCARD/MEMCARD_00_SetIcon.c"
#include "game/MEMCARD/MEMCARD_01_CRC16.c"
// NOTE(aalhendi): CTR_NATIVE routes host-backed card operations through MEMCARD_NativeAdapter; non-native builds use the retail card functions below.
#if defined(CTR_NATIVE)
#include "game/MEMCARD/MEMCARD_NativeAdapter.c"
#else
#include "game/MEMCARD/MEMCARD_16_GetFreeBytes.c"
#include "game/MEMCARD/MEMCARD_18_GetInfo.c"
#include "game/MEMCARD/MEMCARD_21_Format.c"
#include "game/MEMCARD/MEMCARD_22_IsFile.c"
#include "game/MEMCARD/MEMCARD_23_FindFirstGhost.c"
#include "game/MEMCARD/MEMCARD_24_FindNextGhost.c"
#include "game/MEMCARD/MEMCARD_25_EraseFile.c"
#endif
#include "game/MEMCARD/MEMCARD_02_ChecksumSave.c"
#include "game/MEMCARD/MEMCARD_03_ChecksumLoad.c"
#include "game/MEMCARD/MEMCARD_04_StringInit.c"
#include "game/MEMCARD/MEMCARD_05_StringSet.c"
#include "game/MEMCARD/MEMCARD_06_InitCard.c"
#include "game/MEMCARD/MEMCARD_07_CloseCard.c"
#include "game/MEMCARD/MEMCARD_08_GetNextSwEvent.c"
#include "game/MEMCARD/MEMCARD_09_GetNextHwEvent.c"
#include "game/MEMCARD/MEMCARD_10_WaitForHwEvent.c"
#include "game/MEMCARD/MEMCARD_11_SkipEvents.c"
#include "game/MEMCARD/MEMCARD_12_NewTask.c"
#include "game/MEMCARD/MEMCARD_13_CloseFile.c"
#include "game/MEMCARD/MEMCARD_14_ReadFile.c"
#include "game/MEMCARD/MEMCARD_15_WriteFile.c"
#if !defined(CTR_NATIVE)
#include "game/MEMCARD/MEMCARD_17_HandleEvent.c"
#endif
#if !defined(CTR_NATIVE)
#include "game/MEMCARD/MEMCARD_19_Load.c"
#include "game/MEMCARD/MEMCARD_20_Save.c"
#endif

#include "game/MEMPACK.c"

#include "game/MixRNG/PSX_BIOS_Rand.c"
#include "game/MixRNG/RngDeadCoed.c"
#include "game/MixRNG/MixRNG_0_Scramble.c"
#include "game/MixRNG/MixRNG_1_Particles.c"
#include "game/MixRNG/MixRNG_2_GetValue.c"

#include "game/Particle.c"

#include "game/PickupBots/PickupBots_0_Init.c"
#include "game/PickupBots/PickupBots_1_Update.c"

#include "game/PROC.c"

#include "game/PushBuffer.c"

#include "game/QueueLoadTrack.c"

#include "game/Podium/Podium_0_InitModels.c"

#include "game/RaceFlag.c"

#include "game/RECTMENU.c"

#include "game/RaceConfig.c"

#include "game/RefreshCard.c"

#include "game/SelectProfile/SelectProfile_00_QueueLoadHub_MenuProc.c"
#include "game/SelectProfile/SelectProfile_01_ThTick.c"
#include "game/SelectProfile/SelectProfile_02_PrintInteger.c"
#include "game/SelectProfile/SelectProfile_03_UI_ConvertX.c"
#include "game/SelectProfile/SelectProfile_04_UI_ConvertY.c"
#include "game/SelectProfile/SelectProfile_05_DrawAdvProfile.c"
#include "game/SelectProfile/SelectProfile_06_GetTrackID.c"
#include "game/SelectProfile/SelectProfile_07_Init.c"
#include "game/SelectProfile/SelectProfile_08_Destroy.c"
#include "game/SelectProfile/SelectProfile_09_AdvPickMode_MenuProc.c"
#include "game/SelectProfile/SelectProfile_10_DrawGhostProfile.c"
#include "game/SelectProfile/SelectProfile_13_Cursors.c"
#include "game/SelectProfile/SelectProfile_14_ToggleMode.c"
#include "game/SelectProfile/SelectProfile_15_InputLogic.c"
#include "game/SelectProfile/SelectProfile_16_AllProfiles_MenuProc.c"
#include "game/SelectProfile/SelectProfile_17_InitAndDestroy.c"

#include "game/TakeCupProgress.c"

#include "game/SubmitName/SubmitName_0_RestoreName.c"
#include "game/SubmitName/SubmitName_1_DrawMenu.c"
#include "game/SubmitName/SubmitName_2_MenuProc.c"

#include "game/Timer/Timer_0_Init.c"
#include "game/Timer/Timer_1_Destroy.c"
#include "game/Timer/Timer_2_GetTime_Total.c"
#include "game/Timer/Timer_3_GetTime_Elapsed.c"

#include "game/prim.c"
#include "game/math.c"
#include "game/gte.c"
#include "game/MATH/MATH_4_VectorLength.c"
#include "game/MATH/MATH_5_VectorNormalize.c"
#include "game/UI/UI_00_SaveLapTime.c"
#include "game/UI/UI_01_ThTick_CountPickup.c"
#include "game/UI/UI_02_ThTick_Reward.c"
#include "game/UI/UI_03_ThTick_CtrLetters.c"
#include "game/UI/UI_04_ThTick_big1.c"
#include "game/UI/UI_05_ConvertX_2.c"
#include "game/UI/UI_06_ConvertY_2.c"
#include "game/UI/UI_07_INSTANCE_BirthWithThread.c"
#include "game/UI/UI_08_INSTANCE_InitAll.c"
#include "game/UI/UI_09_Map_DrawMap.c"
#include "game/UI/UI_10_Map_GetIconPos.c"
#include "game/UI/UI_11_Map_DrawAdvPlayer.c"
#include "game/UI/UI_12_Map_DrawRawIcon.c"
#include "game/UI/UI_13_Map_DrawDrivers.c"
#include "game/UI/UI_14_Map_DrawGhosts.c"
#include "game/UI/UI_15_Map_DrawTracking.c"
#include "game/UI/UI_16_WeaponBG_AnimateShine.c"
#include "game/UI/UI_17_WeaponBG_DrawShine.c"
#include "game/UI/UI_18_TrackerBG.c"
#include "game/UI/UI_19_DrawDriverIcon.c"
#include "game/UI/UI_20_Lerp2D_Angular.c"
#include "game/UI/UI_21_Lerp2D_HUD.c"
#include "game/UI/UI_22_Lerp2D_Linear.c"
#include "game/UI/UI_23_DrawRaceClock.c"
#include "game/UI/UI_24_DrawLimitClock.c"
#include "game/UI/UI_25_BattleDrawHeadArrows.c"
#include "game/UI/UI_26_TrackerSelf.c"
#include "game/UI/UI_27_DrawPosSuffix.c"
#include "game/UI/UI_28_DrawLapCount.c"
#include "game/UI/UI_29_DrawBattleScores.c"
#include "game/UI/UI_30_Weapon_DrawSelf.c"
#include "game/UI/UI_31_Weapon_DrawBG.c"
#include "game/UI/UI_32_DrawNumWumpa.c"
#include "game/UI/UI_33_DrawNumTimebox.c"
#include "game/UI/UI_34_DrawNumRelic.c"
#include "game/UI/UI_35_DrawNumKey.c"
#include "game/UI/UI_36_DrawNumTrophy.c"
#include "game/UI/UI_37_DrawNumCrystal.c"
#include "game/UI/UI_38_DrawSpeedNeedle.c"
#include "game/UI/UI_39_DrawSpeedBG.c"
#include "game/UI/UI_40_JumpMeter_Update.c"
#include "game/UI/UI_41_JumpMeter_Draw.c"
#include "game/UI/UI_42_DrawSlideMeter.c"
#include "game/UI/UI_43_DrawRankedDrivers.c"
#include "game/UI/UI_44_RenderFrame_Racing.c"
#include "game/UI/UI_45_RenderFrame_AdvHub.c"
#include "game/UI/UI_46_RenderFrame_CrystChall.c"
#include "game/UI/UI_47_RenderFrame_Wumpa3D_2P3P4P.c"
#include "game/UI/UI_48_VsQuipReadDriver.c"
#include "game/UI/UI_49_VsQuipAssign.c"
#include "game/UI/UI_50_VsQuipAssignAll.c"
#include "game/UI/UI_51_VsQuipDrawAll.c"
#include "game/UI/UI_52_VsWaitForPressX.c"
#include "game/UI/UI_53_RaceEnd_GetDriverClock.c"
#include "game/UI/UI_54_RaceStart_IntroText1P.c"
#include "game/UI/UI_55_RaceEnd_MenuProc.c"
#include "game/UI/UI_56_CupStandings_FinalizeCupRanks.c"
#include "game/UI/UI_57_CupStandings_UpdateCupRanks.c"
#include "game/UI/UI_58_CupStandings_InputAndDraw.c"

#include "game/Vehicle/VehBirth_0_TeleportSelf.c"
#include "game/Vehicle/VehBirth_1_TeleportAll.c"
#include "game/Vehicle/VehBirth_2_GetModelByName.c"
#include "game/Vehicle/VehBirth_3_SetConsts.c"
#include "game/Vehicle/VehBirth_4_EngineAudio_AllPlayers.c"
#include "game/Vehicle/VehBirth_5_NullThread.c"
#include "game/Vehicle/VehBirth_6_TireSprites.c"
#include "game/Vehicle/VehBirth_7_NonGhost.c"
#include "game/Vehicle/VehBirth_8_Player.c"

#include "game/Vehicle/VehCalc_0_InterpBySpeed.c"
#include "game/Vehicle/VehCalc_1_MapToRange.c"
#include "game/Vehicle/VehCalc_2_SteerAccel.c"
#include "game/Vehicle/VehCalc_3_FastSqrt.c"

#include "game/Vehicle/VehAfterColl_0_GetSurface.c"
#include "game/Vehicle/VehAfterColl_1_GetTerrain.c"

#include "game/Vehicle/VehEmitter_0_Exhaust.c"
#include "game/Vehicle/VehEmitter_1_Sparks_Ground.c"
#include "game/Vehicle/VehEmitter_2_Terrain_Ground.c"
#include "game/Vehicle/VehEmitter_3_Sparks_Wall.c"
#include "game/Vehicle/VehEmitter_4_DriverMain.c"

#include "game/Vehicle/VehFire_0_Audio.c"
#include "game/Vehicle/VehFire_1_Increment.c"

#include "game/Vehicle/VehFrameInst_0_GetStartFrame.c"
#include "game/Vehicle/VehFrameInst_1_GetNumAnimFrames.c"
#include "game/Vehicle/VehFrameProc_2_Driving.c"
#include "game/Vehicle/VehFrameProc_3_Spinning.c"
#include "game/Vehicle/VehFrameProc_4_LastSpin.c"

#include "game/Vehicle/VehLap_0_UpdateProgress.c"

#include "game/Vehicle/VehPhysCrash_0_ConvertVecToSpeed.c"
#include "game/Vehicle/VehPhysCrash_1_BounceSelf.c"
#include "game/Vehicle/VehPhysCrash_2_AI.c"
#include "game/Vehicle/VehPhysCrash_3_Attack.c"
#include "game/Vehicle/VehPhysCrash_4_AnyTwoCars.c"

#include "game/Vehicle/VehPhysForce_0_ConvertSpeedToVec.c"
#include "game/Vehicle/VehPhysForce_1_OnGravity.c"
#include "game/Vehicle/VehPhysForce_2_OnApplyForces.c"
#include "game/Vehicle/VehPhysForce_3_CollideDrivers.c"
#include "game/Vehicle/VehPhysForce_4_TranslateMatrix.c"
#include "game/Vehicle/VehPhysForce_5_RotAxisAngle.c"
#include "game/Vehicle/VehPhysForce_6_CounterSteer.c"
#include "game/Vehicle/VehGroundShadow_0_Subset1.c"
#include "game/Vehicle/VehGroundShadow_1_Main.c"

#include "game/Vehicle/VehPhysGeneral_0_PhysAngular.c"
#include "game/Vehicle/VehPhysGeneral_1_LerpQuarterStrength.c"
#include "game/Vehicle/VehPhysGeneral_2_LerpToForwards.c"
#include "game/Vehicle/VehPhysGeneral_3_JumpGetVelY.c"
#include "game/Vehicle/VehPhysGeneral_4_JumpAndFriction.c"
#include "game/Vehicle/VehPhysGeneral_5_SetHeldItem.c"
#include "game/Vehicle/VehPhysGeneral_6_GetBaseSpeed.c"

#include "game/Vehicle/VehPhysJoystick_0_ReturnToRest.c"
#include "game/Vehicle/VehPhysJoystick_1_GetStrength.c"
#include "game/Vehicle/VehPhysJoystick_2_GetStrengthAbsolute.c"

#include "game/Vehicle/VehGroundSkids_0_Subset1.c"
#include "game/Vehicle/VehGroundSkids_1_Subset2.c"
#include "game/Vehicle/VehGroundSkids_2_Main.c"

#include "game/Vehicle/VehPhysProc.c"

#include "game/Vehicle/VehPickupItem_0_MaskBoolGoodGuy.c"
#include "game/Vehicle/VehPickupItem_1_MaskUseWeapon.c"
#include "game/Vehicle/VehPickupItem_2_MissileGetTargetDriver.c"
#include "game/Vehicle/VehPickupItem_3_PotionThrow.c"
#include "game/Vehicle/VehPickupItem_4_ShootNow.c"
#include "game/Vehicle/VehPickupItem_5_ShootOnCirclePress.c"
#include "game/Vehicle/VehPickState_0_NewState.c"

#include "game/Vehicle/VehStuckProc.c"

#include "game/Vehicle/VehTurbo_0_ProcessBucket.c"
#include "game/Vehicle/VehTurbo_1_ThDestroy.c"
#include "game/Vehicle/VehTurbo_2_ThTick.c"

#include "game/Vehicle/VehTalkMask_0_ThTick.c"
#include "game/Vehicle/VehTalkMask_1_Init.c"
#include "game/Vehicle/VehTalkMask_2_PlayXA.c"
#include "game/Vehicle/VehTalkMask_3_boolNoXA.c"
#include "game/Vehicle/VehTalkMask_4_End.c"

#include "game/Vector.c"

#include "game/221.c"
#include "game/222.c"
#include "game/223.c"
#include "game/224.c"
#include "game/225.c"

#include "game/221_225_EndEvent.c"

#include "game/PlayLevel/PlayLevel_0_UpdateLapStats.c"

#include "game/230/R230.c"
#include "game/230/D230.c"
#include "game/230/230_Full.c"

#include "game/231/R231.c"
#include "game/231/D231.c"
#include "game/231/231_Full.c"

#include "game/232/R232.c"
#include "game/232/D232.c"

#include "game/232/232_Full.c"

#include "game/233/233_Full.c"

#endif
