#ifndef CTR_NATIVE_NAMESPACE_LOAD_H
#define CTR_NATIVE_NAMESPACE_LOAD_H

enum BigIndex
{
	// 1p, 2p, 4p, relic
	BI_ARCADETRACKS = 0,

	// 1p, 2p, 3p, 4p
	BI_BATTLETRACKS = BI_ARCADETRACKS + (18 * 8),

	// lev, vrm, ptr
	BI_ADVENTUREHUB = BI_BATTLETRACKS + (7 * 8),

	// lev, vrm (menu_models, adv garage, jpnfont)
	BI_MAINMENUFILE = BI_ADVENTUREHUB + (5 * 3),

	// 221-233
	BI_OVERLAYSECT1 = BI_MAINMENUFILE + 6,
	BI_OVERLAYSECT2 = BI_OVERLAYSECT1 + 5,
	BI_OVERLAYSECT3 = BI_OVERLAYSECT2 + 4,

	// LNG for english, french, etc
	BI_LANGUAGEFILE = BI_OVERLAYSECT3 + 4,

	// 0x110 for sep3
	// 0xf2 for all Retails
	BI_RACERMODELHI = BI_LANGUAGEFILE + 8,

	BI_SHAREDMPKVRM = BI_RACERMODELHI + 16,

	BI_1PARCADEPACK = BI_SHAREDMPKVRM + 2,

	BI_ADVENTUREPACK = BI_1PARCADEPACK + 16,

	BI_TIMETRIALPACK = BI_ADVENTUREPACK + 16,

	BI_RACERMODELMED = BI_TIMETRIALPACK + 16,

	BI_2PARCADEPACK = BI_RACERMODELMED + 16,

	BI_RACERMODELLOW = BI_2PARCADEPACK + 8,

	BI_4PARCADEPACK = BI_RACERMODELLOW + 16,

	BI_PODIUMVRMS = BI_4PARCADEPACK + 16,

	BI_DANCEMODELWIN = BI_PODIUMVRMS + 2,

	BI_DANCEMODELLOSE = BI_DANCEMODELWIN + 16 * 2,

	BI_DANCETAWNAGIRL = BI_DANCEMODELLOSE + 16 * 2,

	BI_UKAHEAD = BI_DANCETAWNAGIRL + 4 * 2,

	BI_AKUHEAD = BI_UKAHEAD + 2 * 2,

	BI_DINGOFIRE = BI_AKUHEAD + 2 * 2,

	BI_PODIUM = BI_DINGOFIRE + 2,

	BI_BOSSHEAD = BI_PODIUM + 2,

	BI_LOSEHEAD = BI_BOSSHEAD + 5 * 2,

	BI_BOSSBODY = BI_LOSEHEAD + 5 * 2,

	BI_VLCTABLE = BI_BOSSBODY + 5 * 2,

	BI_THUMBS = BI_VLCTABLE + 1,

	BI_LOADINGSCREENS = BI_THUMBS + 26,

	BI_NDBOX = BI_LOADINGSCREENS + 6,

	BI_CUTSCENES_INTRO = BI_NDBOX + 2,

	BI_CUTSCENES_OUTRO = BI_CUTSCENES_INTRO + 9 * 3,

	BI_CREDITS = BI_CUTSCENES_OUTRO + 2 * 2,

	BI_SCRAPBOOK = BI_CREDITS + 20 * 3
};

struct BigEntry
{
	int offset;
	int size;
};

struct BigHeader
{
	int cdpos;
	int numEntry;

	// "numEntry" number of entries
	// struct BigEntry entry[0];
};
#define BIG_GETENTRY(x) (struct BigEntry *)((char *)(x) + sizeof(struct BigHeader))

enum LoadCdSectorConstants
{
	LOAD_CD_DATA_SECTOR_SHIFT = 11,
	LOAD_CD_DATA_SECTOR_SIZE = 0x800,
	LOAD_CD_DATA_SECTOR_ROUND_MASK = LOAD_CD_DATA_SECTOR_SIZE - 1,
	LOAD_CD_DATA_SECTOR_ALIGN_MASK = -LOAD_CD_DATA_SECTOR_SIZE,
	LOAD_BIGFILE_HEADER_SECTORS = 8,
	LOAD_BIGFILE_HEADER_ALLOC_BYTES = 0x4000,
};

CTR_STATIC_ASSERT(LOAD_CD_DATA_SECTOR_SIZE == 0x800);
CTR_STATIC_ASSERT(LOAD_CD_DATA_SECTOR_ROUND_MASK == 0x7ff);
CTR_STATIC_ASSERT((u32)LOAD_CD_DATA_SECTOR_ALIGN_MASK == 0xfffff800u);
CTR_STATIC_ASSERT(LOAD_BIGFILE_HEADER_SECTORS == 8);
CTR_STATIC_ASSERT(LOAD_BIGFILE_HEADER_ALLOC_BYTES == 0x4000);

enum LoadCharacterConstants
{
	LOAD_CHARACTER_ID_COUNT = 8,
	LOAD_DRIVER_MODEL_EXTRA_COUNT = 3,
	LOAD_MED_LOD_DRIVER_MODEL_EXTRA_COUNT = 2,
	LOAD_2P_AI_SET_RACER_COUNT = 4,
	LOAD_2P_AI_SET_COUNT = 7,
	LOAD_PURPLE_GEM_CUP_AI_SET_INDEX = LOAD_2P_AI_SET_COUNT,
};

CTR_STATIC_ASSERT(LOAD_CHARACTER_ID_COUNT == 8);
CTR_STATIC_ASSERT(LOAD_DRIVER_MODEL_EXTRA_COUNT == 3);
CTR_STATIC_ASSERT(LOAD_MED_LOD_DRIVER_MODEL_EXTRA_COUNT == 2);
CTR_STATIC_ASSERT(LOAD_2P_AI_SET_RACER_COUNT == 4);
CTR_STATIC_ASSERT((LOAD_2P_AI_SET_COUNT * LOAD_2P_AI_SET_RACER_COUNT) == 0x1c);
CTR_STATIC_ASSERT(LOAD_PURPLE_GEM_CUP_AI_SET_INDEX == 7);

enum LoadLevelLod
{
	LOAD_LEVEL_LOD_1P = 1,
	LOAD_LEVEL_LOD_2P = 2,
	LOAD_LEVEL_LOD_3P = 3,
	LOAD_LEVEL_LOD_4P = 4,
	LOAD_LEVEL_LOD_3P4P_COUNT = LOAD_LEVEL_LOD_4P - LOAD_LEVEL_LOD_3P + 1,
	LOAD_LEVEL_LOD_RELIC = 8,
};

CTR_STATIC_ASSERT(LOAD_LEVEL_LOD_1P == 1);
CTR_STATIC_ASSERT(LOAD_LEVEL_LOD_2P == 2);
CTR_STATIC_ASSERT(LOAD_LEVEL_LOD_3P == 3);
CTR_STATIC_ASSERT(LOAD_LEVEL_LOD_4P == 4);
CTR_STATIC_ASSERT(LOAD_LEVEL_LOD_3P4P_COUNT == 2);
CTR_STATIC_ASSERT(LOAD_LEVEL_LOD_RELIC == 8);

enum LoadBigfileGroupConstants
{
	LOAD_TRACK_FILES_PER_LOD_GROUP = 8,
	LOAD_CUTSCENE_FILES_PER_LEVEL = 3,
	LOAD_OUTRO_FILES_PER_LEVEL = 2,
	LOAD_BATTLE_TRACK_COUNT = 7,
	LOAD_INTRO_CUTSCENE_COUNT = 9,
	LOAD_OUTRO_CUTSCENE_COUNT = 2,
	LOAD_CREDIT_LEVEL_COUNT = 20,
	LOAD_MAIN_MENU_GARAGE_FILE_OFFSET = 2,
};

CTR_STATIC_ASSERT(LOAD_TRACK_FILES_PER_LOD_GROUP == 8);
CTR_STATIC_ASSERT(LOAD_CUTSCENE_FILES_PER_LEVEL == 3);
CTR_STATIC_ASSERT(LOAD_OUTRO_FILES_PER_LEVEL == 2);
CTR_STATIC_ASSERT(LOAD_BATTLE_TRACK_COUNT == 7);
CTR_STATIC_ASSERT(LOAD_INTRO_CUTSCENE_COUNT == 9);
CTR_STATIC_ASSERT(LOAD_OUTRO_CUTSCENE_COUNT == 2);
CTR_STATIC_ASSERT(LOAD_CREDIT_LEVEL_COUNT == 20);
CTR_STATIC_ASSERT(LOAD_MAIN_MENU_GARAGE_FILE_OFFSET == 2);

enum LoadHubConstants
{
	LOAD_ADV_HUB_COUNT = 5,
	LOAD_ADV_HUB_CONNECTION_COUNT = 3,
	LOAD_HUB_TRIGGER_NONE = 0,
	LOAD_HUB_TRIGGER_ID_BIAS = 1,
	LOAD_HUB_MEMPACK_PAIR_INDEX_SUM = 3,
	LOAD_HUB_PATCH_MEM_ACTIVE = 1,
};

CTR_STATIC_ASSERT(LOAD_ADV_HUB_COUNT == 5);
CTR_STATIC_ASSERT(LOAD_ADV_HUB_CONNECTION_COUNT == 3);
CTR_STATIC_ASSERT(LOAD_HUB_TRIGGER_NONE == 0);
CTR_STATIC_ASSERT(LOAD_HUB_TRIGGER_ID_BIAS == 1);
CTR_STATIC_ASSERT(LOAD_HUB_MEMPACK_PAIR_INDEX_SUM == 3);
CTR_STATIC_ASSERT(LOAD_HUB_PATCH_MEM_ACTIVE == 1);

enum LoadQueueConstants
{
	LOAD_QUEUE_SLOT_COUNT = 8,
	LOAD_QUEUE_FIRST_PENDING_SLOT = 1,
	LOAD_QUEUE_VRAM_CALLBACK_DELAY_FRAMES = 3,
};

CTR_STATIC_ASSERT(LOAD_QUEUE_SLOT_COUNT == 8);
CTR_STATIC_ASSERT(LOAD_QUEUE_FIRST_PENDING_SLOT == 1);
CTR_STATIC_ASSERT(LOAD_QUEUE_VRAM_CALLBACK_DELAY_FRAMES == 3);

enum LoadTenStagesConstants
{
	LOAD_FIRST_BOOT_COPYRIGHT_TIM_BIGFILE_INDEX = 0x1fe,

	LOAD_LEVEL_PREFIX_NDI_LENGTH = 3,
	LOAD_LEVEL_PREFIX_ENDING_LENGTH = 6,
	LOAD_LEVEL_PREFIX_INTRO_LENGTH = 5,
	LOAD_LEVEL_PREFIX_SCREEN_LENGTH = 6,
	LOAD_LEVEL_PREFIX_GARAGE_LENGTH = 6,
	LOAD_LEVEL_PREFIX_HUB_LENGTH = 3,
	LOAD_LEVEL_PREFIX_CREDIT_LENGTH = 6,

	LOAD_MAIN_PACK_INDEX = 0,
	LOAD_FIRST_SUBPACK_INDEX = 1,
	LOAD_SECOND_SUBPACK_INDEX = 2,
	LOAD_NO_LEVEL_IN_MEMPACK = -1,

	LOAD_CUTSCENE_FIRST_PACK_BYTES = 0x6b000,
	LOAD_CUTSCENE_SECOND_PACK_BYTES = 0x40000,
	LOAD_ADV_ARENA_FIRST_PACK_BYTES = 0x68800,
	LOAD_ADV_ARENA_SECOND_PACK_BYTES = 0x68800,

	LOAD_PTR_MAP_ADV_LEVEL_COUNT = 0xe,
	LOAD_PTR_MAP_CREDIT_LEVEL_COUNT = LOAD_CREDIT_LEVEL_COUNT,

	LOAD_MODEL_FILE_HEADER_BYTES = 4,
	LOAD_PODIUM_MODEL_SLOT_COUNT = 8,
	LOAD_PODIUM_LAST_MODEL_SLOT = LOAD_PODIUM_MODEL_SLOT_COUNT - 1,
	LOAD_PODIUM_MODELS_WITH_FILE_HEADER = 7,
	LOAD_PODIUM_MODEL_FILE_STRIDE = 2,

	LOAD_POSTLOAD_AUDIO_OXIDE_INTRO = 3,
	LOAD_POSTLOAD_AUDIO_NDBOX = 4,
};

CTR_STATIC_ASSERT(LOAD_FIRST_BOOT_COPYRIGHT_TIM_BIGFILE_INDEX == 0x1fe);
CTR_STATIC_ASSERT(LOAD_LEVEL_PREFIX_NDI_LENGTH == 3);
CTR_STATIC_ASSERT(LOAD_LEVEL_PREFIX_ENDING_LENGTH == 6);
CTR_STATIC_ASSERT(LOAD_LEVEL_PREFIX_INTRO_LENGTH == 5);
CTR_STATIC_ASSERT(LOAD_LEVEL_PREFIX_SCREEN_LENGTH == 6);
CTR_STATIC_ASSERT(LOAD_LEVEL_PREFIX_GARAGE_LENGTH == 6);
CTR_STATIC_ASSERT(LOAD_LEVEL_PREFIX_HUB_LENGTH == 3);
CTR_STATIC_ASSERT(LOAD_LEVEL_PREFIX_CREDIT_LENGTH == 6);
CTR_STATIC_ASSERT(LOAD_MAIN_PACK_INDEX == 0);
CTR_STATIC_ASSERT(LOAD_FIRST_SUBPACK_INDEX == 1);
CTR_STATIC_ASSERT(LOAD_SECOND_SUBPACK_INDEX == 2);
CTR_STATIC_ASSERT((u16)LOAD_NO_LEVEL_IN_MEMPACK == 0xffff);
CTR_STATIC_ASSERT(LOAD_CUTSCENE_FIRST_PACK_BYTES == 0x6b000);
CTR_STATIC_ASSERT(LOAD_CUTSCENE_SECOND_PACK_BYTES == 0x40000);
CTR_STATIC_ASSERT(LOAD_ADV_ARENA_FIRST_PACK_BYTES == 0x68800);
CTR_STATIC_ASSERT(LOAD_ADV_ARENA_SECOND_PACK_BYTES == 0x68800);
CTR_STATIC_ASSERT(LOAD_PTR_MAP_ADV_LEVEL_COUNT == 0xe);
CTR_STATIC_ASSERT(LOAD_PTR_MAP_CREDIT_LEVEL_COUNT == 0x14);
CTR_STATIC_ASSERT(LOAD_MODEL_FILE_HEADER_BYTES == 4);
CTR_STATIC_ASSERT(LOAD_PODIUM_MODEL_SLOT_COUNT == 8);
CTR_STATIC_ASSERT(LOAD_PODIUM_LAST_MODEL_SLOT == 7);
CTR_STATIC_ASSERT(LOAD_PODIUM_MODELS_WITH_FILE_HEADER == 7);
CTR_STATIC_ASSERT(LOAD_PODIUM_MODEL_FILE_STRIDE == 2);
CTR_STATIC_ASSERT(LOAD_POSTLOAD_AUDIO_OXIDE_INTRO == 3);
CTR_STATIC_ASSERT(LOAD_POSTLOAD_AUDIO_NDBOX == 4);

struct DramPointerMap
{
	int numBytes;

	// int offsets[0];
};

#define DRAM_GETOFFSETS(x) ((int *)((char *)(x) + sizeof(struct DramPointerMap)))

enum DramPointerMapConstants
{
	DRAM_POINTER_MAP_WORD_SHIFT = 2,
};

CTR_STATIC_ASSERT(sizeof(struct DramPointerMap) == 4);
CTR_STATIC_ASSERT(DRAM_POINTER_MAP_WORD_SHIFT == 2);

#define DRAM_SET_UNPATCHED(x) *(int *)x = 0

#define DRAM_SET_PATCHED(x)   *(int *)x = *(int *)x | 0x10000000;

#define DRAM_IS_PATCHED(x)    ((*(int *)((u32)x - 4) & 0x10000000) != 0)

struct VramHeader
{
	char data[0xC];

	// 0xC
	RECT rect;

	// 0x14
	// u8 pixels[0];
};

#define VRAMHEADER_GETPIXLES(x) (u32 *)((char *)(x) + sizeof(struct VramHeader))

enum LevVramIndex
{
	LVI_VRAM = 0,
	LVI_LEV = 1,
	LVI_PTR = 2,
};

// For modding OG game,
// not in decompile
enum LoadTypeLegacy
{
	// ordinary read to ram
	LT_RAW = 1,

	// read with pointer map at the end
	LT_DRAM = 2,

	// read with vram transfer
	LT_VRAM = 3
};

// New system
enum LoadType
{
	// load to specified ram address
	LT_SETADDR = 0x1,

	// get result of mempack_allocmem
	LT_GETADDR = 0x2,

	// send to vram
	LT_SETVRAM = 0x4,

	// === BITWISE OR ===

	// blocking read
	LT_SYNC = 0x10,

	// non-blocking read
	LT_ASYNC = 0x20,

	// === BITWISE OR ===
	LT_MEMPACK = 0x100,
};

struct LoadQueueSlot
{
	// 0x0
	struct BigHeader *ptrBigfileCdPos_UNUSED;

	// 0x4
	u16 flags;

	// 0x6
	u16 type_UNUSED;

	// 0x8
	u32 subfileIndex;

	// 0xC
	void *ptrDestination;

	// 0x10
	u32 size_UNUSED;

	// 0x14
	void (*callbackFuncPtr)(struct LoadQueueSlot *);
};

#define LOAD_QUEUE_CALLBACK_SET_POINTER ((void (*)(struct LoadQueueSlot *)) - 2)

CTR_STATIC_ASSERT(sizeof(struct LoadQueueSlot) == 0x18);

#endif
