#ifndef CTR_NATIVE_NAMESPACE_LNG_H
#define CTR_NATIVE_NAMESPACE_LNG_H

// Generated from assets/bigfile/lang/en.lng. Values are retail LNG string indices.
enum LngStringId
{
	LNG_PAUSED = 0x000,                     // PAUSED
	LNG_RESTART = 0x001,                    // RESTART
	LNG_RESUME = 0x002,                     // RESUME
	LNG_QUIT = 0x003,                       // QUIT
	LNG_RETRY = 0x004,                      // RETRY
	LNG_CHANGE_CHARACTER = 0x005,           // CHANGE CHARACTER
	LNG_CHANGE_LEVEL = 0x006,               // CHANGE LEVEL
	LNG_CHANGE_CART = 0x007,                // CHANGE CART
	LNG_SAVE_TIME = 0x008,                  // SAVE TIME
	LNG_SAVE_GHOST = 0x009,                 // SAVE GHOST
	LNG_CHANGE_SETUP = 0x00a,               // CHANGE SETUP
	LNG_AKU_AKU_HINTS = 0x00b,              // AKU AKU HINTS
	LNG_UKA_UKA_HINTS = 0x00c,              // UKA UKA HINTS
	LNG_EXIT_TO_MAP = 0x00d,                // EXIT TO MAP
	LNG_OPTIONS = 0x00e,                    // OPTIONS
	LNG_GEMS = 0x00f,                       // GEMS
	LNG_CTR_TOKENS = 0x010,                 // CTR TOKENS
	LNG_RELICS = 0x011,                     // RELICS
	LNG_TIME = 0x012,                       // TIME
	LNG_TIMING_OUT_EXITING_DEMO = 0x013,    // Timing Out - Exiting Demo
	LNG_UNUSED_014 = 0x014,                 //
	LNG_UNUSED_015 = 0x015,                 //
	LNG_HITPTS = 0x016,                     // HITPTS
	LNG_POINTS = 0x017,                     // POINTS
	LNG_LAP = 0x018,                        // LAP
	LNG_ST = 0x019,                         // ST
	LNG_ND = 0x01a,                         // ND
	LNG_RD = 0x01b,                         // RD
	LNG_TH = 0x01c,                         // TH
	LNG_WRONG_WAY = 0x01d,                  // WRONG WAY!
	LNG_FINISHED = 0x01e,                   // FINISHED!
	LNG_CONTROLLER_1_IS_UNPLUGGED = 0x01f,  // CONTROLLER 1 IS UNPLUGGED!
	LNG_CONTROLLER_2_IS_UNPLUGGED = 0x020,  // CONTROLLER 2 IS UNPLUGGED!
	LNG_CONTROLLER_1A_IS_UNPLUGGED = 0x021, // CONTROLLER 1A IS UNPLUGGED!
	LNG_CONTROLLER_1B_IS_UNPLUGGED = 0x022, // CONTROLLER 1B IS UNPLUGGED!
	LNG_CONTROLLER_1C_IS_UNPLUGGED = 0x023, // CONTROLLER 1C IS UNPLUGGED!
	LNG_CONTROLLER_1D_IS_UNPLUGGED = 0x024, // CONTROLLER 1D IS UNPLUGGED!
	LNG_YOU_MUST_HAVE_A_CONTROLLER_PLUGGED_INTO_CONTROLLER =
	    0x025, // YOU MUST HAVE A CONTROLLER PLUGGED INTO CONTROLLER PORT 1 TO PLAY A ONE PLAYER GAME.  PLEASE PLUG IN A CONT...
	LNG_YOU_MUST_HAVE_CONTROLLERS_PLUGGED_INTO_CONTROLLER_PORTS =
	    0x026, // YOU MUST HAVE CONTROLLERS PLUGGED INTO CONTROLLER PORTS 1 AND 2 TO PLAY A TWO PLAYER GAME.  PLEASE PLUG IN ...
	LNG_YOU_MUST_HAVE_A_CONTROLLER_PLUGGED_INTO_CONTROLLER_027 =
	    0x027, // YOU MUST HAVE A CONTROLLER PLUGGED INTO CONTROLLER PORT 1A TO PLAY A ONE PLAYER GAME.  PLEASE PLUG IN A CON...
	LNG_YOU_MUST_HAVE_CONTROLLERS_PLUGGED_INTO_CONTROLLER_PORTS_028 =
	    0x028, // YOU MUST HAVE CONTROLLERS PLUGGED INTO CONTROLLER PORTS 1A AND 1B TO PLAY A TWO PLAYER GAME.  PLEASE PLUG I...
	LNG_YOU_MUST_HAVE_A_MULTI_TAP_PLUGGED_INTO =
	    0x029, // YOU MUST HAVE A MULTI TAP PLUGGED INTO CONTROLLER PORT 1 AND CONTROLLERS PLUGGED INTO CONTROLLERS PORTS 1A,...
	LNG_YOU_MUST_HAVE_A_MULTI_TAP_PLUGGED_INTO_02A =
	    0x02a,                              // YOU MUST HAVE A MULTI TAP PLUGGED INTO CONTROLLER PORT 1 AND CONTROLLERS PLUGGED INTO CONTROLLERS PORTS 1A,...
	LNG_PLEASE_INSERT_A_CONTROLLER = 0x02b, // PLEASE INSERT A CONTROLLER
	LNG_CRASH_BANDICOOT = 0x02c,            // CRASH BANDICOOT
	LNG_DR_NEO_CORTEX = 0x02d,              // DR. NEO CORTEX
	LNG_TINY_TIGER = 0x02e,                 // TINY TIGER
	LNG_COCO_BANDICOOT = 0x02f,             // COCO BANDICOOT
	LNG_N_GIN_FULL = 0x030,                 // N. GIN
	LNG_DINGODILE = 0x031,                  // DINGODILE
	LNG_POLAR_FULL = 0x032,                 // POLAR
	LNG_PURA_FULL = 0x033,                  // PURA
	LNG_PINSTRIPE = 0x034,                  // PINSTRIPE
	LNG_PAPU_PAPU = 0x035,                  // PAPU PAPU
	LNG_RIPPER_ROO = 0x036,                 // RIPPER ROO
	LNG_KOMODO_JOE = 0x037,                 // KOMODO JOE
	LNG_DR_N_TROPY = 0x038,                 // DR. N. TROPY
	LNG_N_OXIDE_FULL = 0x039,               // N. OXIDE
	LNG_PENTA_PENGUIN = 0x03a,              // PENTA PENGUIN
	LNG_FAKE_CRASH = 0x03b,                 // FAKE CRASH
	LNG_CRASH = 0x03c,                      // CRASH
	LNG_N_CORTEX = 0x03d,                   // N.CORTEX
	LNG_TINY = 0x03e,                       // TINY
	LNG_COCO = 0x03f,                       // COCO
	LNG_N_GIN_SHORT = 0x040,                // N. GIN
	LNG_DINGO = 0x041,                      // DINGO
	LNG_POLAR_SHORT = 0x042,                // POLAR
	LNG_PURA_SHORT = 0x043,                 // PURA
	LNG_P_STRIPE = 0x044,                   // P.STRIPE
	LNG_PAPU = 0x045,                       // PAPU
	LNG_ROO = 0x046,                        // ROO
	LNG_KOMODO_J = 0x047,                   // KOMODO.J
	LNG_N_TROPY = 0x048,                    // N. TROPY
	LNG_N_OXIDE_SHORT = 0x049,              // N. OXIDE
	LNG_PENGUIN = 0x04a,                    // PENGUIN
	LNG_F_CRASH = 0x04b,                    // F. CRASH
	LNG_ADVENTURE = 0x04c,                  // ADVENTURE
	LNG_TIME_TRIAL = 0x04d,                 // TIME TRIAL
	LNG_ARCADE = 0x04e,                     // ARCADE
	LNG_VS = 0x04f,                         // VS.
	LNG_BATTLE = 0x050,                     // BATTLE
	LNG_HIGH_SCORE = 0x051,                 // HIGH SCORE
	LNG_LANGUAGE = 0x052,                   // LANGUAGE
	LNG_PLAYERS = 0x053,                    // PLAYERS
	LNG_1P = 0x054,                         // 1P
	LNG_2P = 0x055,                         // 2P
	LNG_3P = 0x056,                         // 3P
	LNG_4P = 0x057,                         // 4P
	LNG_PLAYER_1 = 0x058,                   // PLAYER 1
	LNG_PLAYER_2 = 0x059,                   // PLAYER 2
	LNG_PLAYER_3 = 0x05a,                   // PLAYER 3
	LNG_PLAYER_4 = 0x05b,                   // PLAYER 4
	LNG_CAR_TYPE = 0x05c,                   // CAR TYPE
	LNG_STANDARD = 0x05d,                   // STANDARD
	LNG_UNLIMITED = 0x05e,                  // UNLIMITED
	LNG_SELECT_CHARACTER = 0x05f,           // SELECT CHARACTER
	LNG_SELECT_CHARACTER_SELECT = 0x060,    // SELECT
	LNG_CHARACTER = 0x061,                  // CHARACTER
	LNG_NITRO_COURT = 0x062,                // NITRO COURT
	LNG_RAMPAGE_RUINS = 0x063,              // RAMPAGE RUINS
	LNG_PARKING_LOT = 0x064,                // PARKING LOT
	LNG_SKULL_ROCK = 0x065,                 // SKULL ROCK
	LNG_THE_NORTH_BOWL = 0x066,             // THE NORTH BOWL
	LNG_ROCKY_ROAD = 0x067,                 // ROCKY ROAD
	LNG_LAB_BASEMENT = 0x068,               // LAB BASEMENT
	LNG_SELECT_LEVEL_SELECT = 0x069,        // SELECT
	LNG_LEVEL = 0x06a,                      // LEVEL
	LNG_GHOST_DATA_EXISTS = 0x06b,          // GHOST DATA EXISTS
	LNG_NO_GHOST = 0x06c,                   // NO GHOST
	LNG_NOT_AVAILABLE = 0x06d,              // NOT AVAILABLE
	LNG_DINGO_CANYON = 0x06e,               // DINGO CANYON
	LNG_DRAGON_MINES = 0x06f,               // DRAGON MINES
	LNG_BLIZZARD_BLUFF = 0x070,             // BLIZZARD BLUFF
	LNG_CRASH_COVE = 0x071,                 // CRASH COVE
	LNG_TIGER_TEMPLE = 0x072,               // TIGER TEMPLE
	LNG_PAPUS_PYRAMID = 0x073,              // PAPU'S PYRAMID
	LNG_ROOS_TUBES = 0x074,                 // ROO'S TUBES
	LNG_HOT_AIR_SKYWAY = 0x075,             // HOT AIR SKYWAY
	LNG_SEWER_SPEEDWAY = 0x076,             // SEWER SPEEDWAY
	LNG_MYSTERY_CAVES = 0x077,              // MYSTERY CAVES
	LNG_CORTEX_CASTLE = 0x078,              // CORTEX CASTLE
	LNG_N_GIN_LABS = 0x079,                 // N.GIN LABS
	LNG_POLAR_PASS = 0x07a,                 // POLAR PASS
	LNG_OXIDE_STATION = 0x07b,              // OXIDE STATION
	LNG_COCO_PARK = 0x07c,                  // COCO PARK
	LNG_TINY_ARENA = 0x07d,                 // TINY ARENA
	LNG_SLIDE_COLISEUM = 0x07e,             // SLIDE COLISEUM
	LNG_TURBO_TRACK = 0x07f,                // TURBO TRACK
	LNG_GEM_STONE_VALLEY = 0x080,           // GEM STONE VALLEY
	LNG_N_SANITY_BEACH = 0x081,             // N.SANITY BEACH
	LNG_THE_LOST_RUINS = 0x082,             // THE LOST RUINS
	LNG_GLACIER_PARK = 0x083,               // GLACIER PARK
	LNG_CITADEL_CITY = 0x084,               // CITADEL CITY
	LNG_ENGLISH = 0x085,                    // ENGLISH
	LNG_FRENCH = 0x086,                     // FRENCH
	LNG_GERMAN = 0x087,                     // GERMAN
	LNG_ITALIAN = 0x088,                    // ITALIAN
	LNG_SPANISH = 0x089,                    // SPANISH
	LNG_DUTCH = 0x08a,                      // DUTCH
	LNG_BABYTALK = 0x08b,                   // BABYTALK
	LNG_ESPERANTO = 0x08c,                  // ESPERANTO
	LNG_NEW = 0x08d,                        // NEW
	LNG_MEMCARD_LOAD = 0x08e,               // LOAD
	LNG_BATTLE_SELECT_CHARACTER = 0x08f,    // SELECT CHARACTER
	LNG_SETUP_BATTLE = 0x090,               // SETUP BATTLE
	LNG_TYPE = 0x091,                       // TYPE:
	LNG_POINT_LIMIT_MODE = 0x092,           // POINT LIMIT MODE
	LNG_TIME_LIMIT_MODE = 0x093,            // TIME LIMIT MODE
	LNG_LIFE_LIMIT_MODE = 0x094,            // LIFE LIMIT MODE
	LNG_LENGTH = 0x095,                     // LENGTH:
	LNG_POINTS_096 = 0x096,                 // POINTS:
	LNG_HIT_POINTS = 0x097,                 // HIT POINTS:
	LNG_TEAMS = 0x098,                      // TEAMS:
	LNG_WEAPONS = 0x099,                    // WEAPONS:
	LNG_LAPS = 0x09a,                       // LAPS
	LNG_BATTLE_LAPS_3 = 0x09b,              // 3
	LNG_BATTLE_LAPS_5 = 0x09c,              // 5
	LNG_BATTLE_LAPS_7 = 0x09d,              // 7
	LNG_3_LIVES = 0x09e,                    // 3 LIVES
	LNG_6_LIVES = 0x09f,                    // 6 LIVES
	LNG_9_LIVES = 0x0a0,                    // 9 LIVES
	LNG_5_POINTS = 0x0a1,                   // 5 POINTS
	LNG_10_POINTS = 0x0a2,                  // 10 POINTS
	LNG_15_POINTS = 0x0a3,                  // 15 POINTS
	LNG_POINT_LIMIT_3_MINUTES = 0x0a4,      // 3 MINUTES
	LNG_POINT_LIMIT_6_MINUTES = 0x0a5,      // 6 MINUTES
	LNG_FOREVER = 0x0a6,                    // FOREVER
	LNG_TIME_LIMIT_3_MINUTES = 0x0a7,       // 3 MINUTES
	LNG_TIME_LIMIT_6_MINUTES = 0x0a8,       // 6 MINUTES
	LNG_9_MINUTES = 0x0a9,                  // 9 MINUTES
	LNG_TEAMS_ERROR_LINE1 = 0x0aa,          // THERE MUST BE
	LNG_TWO_OR_MORE_TEAMS = 0x0ab,          // TWO OR MORE TEAMS
	LNG_WEAPONS_ERROR_LINE1 = 0x0ac,        // THERE MUST BE
	LNG_AT_LEAST_ONE_WEAPON = 0x0ad,        // AT LEAST ONE WEAPON
	LNG_START_BATTLE = 0x0ae,               // START BATTLE
	LNG_TIME_TRIAL_MENU = 0x0af,            // TIME TRIAL
	LNG_TIME_TRIAL_UNLIMITED = 0x0b0,       // UNLIMITED
	LNG_TIME_TRIAL_RELIC_RACE = 0x0b1,      // RELIC RACE
	LNG_TIME_TRIAL_EXIT = 0x0b2,            // EXIT
	LNG_BEST_TRACK_TIMES = 0x0b3,           // BEST TRACK TIMES:
	LNG_BEST_LAP_TIME = 0x0b4,              // BEST LAP TIME:
	LNG_EMPTY = 0x0b5,                      // EMPTY
	LNG_CHOOSE_RACE_TYPE = 0x0b6,           // CHOOSE RACE TYPE
	LNG_TROPHY_RACE = 0x0b7,                // TROPHY RACE
	LNG_RELIC_RACE = 0x0b8,                 // RELIC RACE
	LNG_RED_GEM_CUP = 0x0b9,                // RED GEM CUP
	LNG_GREEN_GEM_CUP = 0x0ba,              // GREEN GEM CUP
	LNG_BLUE_GEM_CUP = 0x0bb,               // BLUE GEM CUP
	LNG_YELLOW_GEM_CUP = 0x0bc,             // YELLOW GEM CUP
	LNG_PURPLE_GEM_CUP = 0x0bd,             // PURPLE GEM CUP
	LNG_BONUS_ROUND = 0x0be,                // BONUS ROUND
	LNG_SELECT_CUP_RACE = 0x0bf,            // SELECT CUP RACE
	LNG_WUMPA_CUP = 0x0c0,                  // WUMPA CUP
	LNG_CRYSTAL_CUP = 0x0c1,                // CRYSTAL CUP
	LNG_NITRO_CUP = 0x0c2,                  // NITRO CUP
	LNG_CRASH_CUP = 0x0c3,                  // CRASH CUP
	LNG_TOTAL = 0x0c4,                      // TOTAL
	LNG_YOUR_TIME = 0x0c5,                  // YOUR TIME
	LNG_SAPPHIRE = 0x0c6,                   // SAPPHIRE
	LNG_GOLD = 0x0c7,                       // GOLD
	LNG_PLATINUM = 0x0c8,                   // PLATINUM
	LNG_PRESS_TO_CONTINUE = 0x0c9,          // PRESS * TO CONTINUE
	LNG_STANDINGS = 0x0ca,                  // STANDINGS
	LNG_MEMCARD_LOAD_ACTION = 0x0cb,        // LOAD
	LNG_MEMCARD_SAVE_ACTION = 0x0cc,        // SAVE
	LNG_DELETE = 0x0cd,                     // DELETE
	LNG_MEMCARD_EXIT = 0x0ce,               // EXIT
	LNG_INSERT_ANY_MEMORY_CARD_WITH_GHOST_DATA_IN = 0x0cf, // INSERT ANY MEMORY CARD WITH GHOST DATA IN MEMORY CARD SLOT 1
	LNG_DATA_ON_MEMORY_CARD_IS_OUT_OF_DATE = 0x0d0,        // ...DATA ON MEMORY CARD IS OUT OF DATE...
	LNG_OVERWRITE = 0x0d1,                                 // OVERWRITE?
	LNG_YES = 0x0d2,                                       // YES
	LNG_NO = 0x0d3,                                        // NO
	LNG_SAVE_GAME_CHOOSE_MEMORY_CARD_SLOT = 0x0d4,         // CHOOSE A MEMORY CARD SLOT
	LNG_SAVE_GAME_TO_SAVE_TO = 0x0d5,                      // TO SAVE TO
	LNG_LOAD_GAME_CHOOSE_GAME = 0x0d6,                     // CHOOSE A GAME
	LNG_LOAD_GAME_TO_LOAD = 0x0d7,                         // TO LOAD
	LNG_DELETE_GAME_CHOOSE_GAME = 0x0d8,                   // CHOOSE A GAME
	LNG_DELETE_GAME_TO_DELETE = 0x0d9,                     // TO DELETE
	LNG_SAVE_GHOST_CHOOSE_MEMORY_CARD_SLOT = 0x0da,        // CHOOSE A MEMORY CARD SLOT
	LNG_SAVE_GHOST_TO_SAVE_TO = 0x0db,                     // TO SAVE TO
	LNG_LOAD_GHOST_CHOOSE_GHOST = 0x0dc,                   // CHOOSE A GHOST
	LNG_LOAD_GHOST_TO_LOAD = 0x0dd,                        // TO LOAD
	LNG_DELETE_GHOST_CHOOSE_GHOST = 0x0de,                 // CHOOSE A GHOST
	LNG_DELETE_GHOST_TO_DELETE = 0x0df,                    // TO DELETE
	LNG_MEMCARD_CHECKING = 0x0e0,                          // CHECKING...
	LNG_FORMATTING = 0x0e1,                                // FORMATTING...
	LNG_FORMAT_DO_NOT_REMOVE = 0x0e2,                      // DO NOT REMOVE
	LNG_FORMAT_THE_MEMORY_CARD = 0x0e3,                    // THE MEMORY CARD!
	LNG_UNUSED_0E4 = 0x0e4,                                //
	LNG_UNUSED_0E5 = 0x0e5,                                //
	LNG_UNUSED_0E6 = 0x0e6,                                //
	LNG_UNUSED_0E7 = 0x0e7,                                //
	LNG_UNUSED_0E8 = 0x0e8,                                //
	LNG_UNUSED_0E9 = 0x0e9,                                //
	LNG_SAVING_TO_MEMORY_CARD = 0x0ea,                     // SAVING TO MEMORY CARD...
	LNG_SAVE_DO_NOT_REMOVE = 0x0eb,                        // DO NOT REMOVE
	LNG_SAVE_THE_MEMORY_CARD = 0x0ec,                      // THE MEMORY CARD!
	LNG_UNUSED_0ED = 0x0ed,                                //
	LNG_UNUSED_0EE = 0x0ee,                                //
	LNG_UNUSED_0EF = 0x0ef,                                //
	LNG_UNUSED_0F0 = 0x0f0,                                //
	LNG_UNUSED_0F1 = 0x0f1,                                //
	LNG_UNUSED_0F2 = 0x0f2,                                //
	LNG_MEMCARD_LOADING = 0x0f3,                           // LOADING..
	LNG_UNUSED_0F4 = 0x0f4,                                //
	LNG_UNUSED_0F5 = 0x0f5,                                //
	LNG_UNUSED_0F6 = 0x0f6,                                //
	LNG_UNUSED_0F7 = 0x0f7,                                //
	LNG_UNUSED_0F8 = 0x0f8,                                //
	LNG_UNUSED_0F9 = 0x0f9,                                //
	LNG_UNUSED_0FA = 0x0fa,                                //
	LNG_UNUSED_0FB = 0x0fb,                                //
	LNG_DELETING_GAME_SLOT = 0x0fc,                        // DELETING GAME SLOT...
	LNG_DELETE_DO_NOT_REMOVE = 0x0fd,                      // DO NOT REMOVE
	LNG_DELETE_THE_MEMORY_CARD = 0x0fe,                    // THE MEMORY CARD!
	LNG_UNUSED_0FF = 0x0ff,                                //
	LNG_UNUSED_100 = 0x100,                                //
	LNG_UNUSED_101 = 0x101,                                //
	LNG_UNUSED_102 = 0x102,                                //
	LNG_UNUSED_103 = 0x103,                                //
	LNG_UNUSED_104 = 0x104,                                //
	LNG_MEMCARD_CHECKING_2DOTS = 0x105,                    // CHECKING..
	LNG_NO_MEMCARD_WARNING_TITLE = 0x106,                  // WARNING:
	LNG_NO_MEMCARD_LINE1 = 0x107,                          // THERE IS NO MEMORY CARD
	LNG_NO_MEMCARD_LINE2 = 0x108,                          // IN MEMORY CARD SLOT 1.
	LNG_NO_MEMCARD_LINE3 = 0x109,                          // PLEASE INSERT A MEMORY CARD.
	LNG_UNUSED_10A = 0x10a,                                //
	LNG_NO_MEMCARD_PRESS_TO_CONTINUE = 0x10b,              // PRESS * TO CONTINUE
	LNG_WITHOUT_SAVING = 0x10c,                            // WITHOUT SAVING.
	LNG_UNUSED_10D = 0x10d,                                //
	LNG_UNUSED_10E = 0x10e,                                //
	LNG_NO_MEMCARD_WARNING_TITLE_2 = 0x10f,                // WARNING:
	LNG_NO_MEMCARD_LINE1_2 = 0x110,                        // THERE IS NO MEMORY CARD
	LNG_NO_MEMCARD_LINE2_2 = 0x111,                        // IN MEMORY CARD SLOT 1.
	LNG_NO_MEMCARD_LINE3_2 = 0x112,                        // PLEASE INSERT A MEMORY CARD.
	LNG_UNUSED_113 = 0x113,                                //
	LNG_UNUSED_114 = 0x114,                                //
	LNG_UNUSED_115 = 0x115,                                //
	LNG_UNUSED_116 = 0x116,                                //
	LNG_UNUSED_117 = 0x117,                                //
	LNG_UNFORMATTED_MEMCARD_WARNING_TITLE = 0x118,         // WARNING:
	LNG_UNFORMATTED_MEMCARD_LINE1 = 0x119,                 // THE MEMORY CARD IN
	LNG_MEMORY_CARD_SLOT_1 = 0x11a,                        // MEMORY CARD SLOT 1
	LNG_IS_UNFORMATTED = 0x11b,                            // IS UNFORMATTED
	LNG_PRESS_CROSS_TO_FORMAT = 0x11c,                     // PRESS @ TO FORMAT.
	LNG_OR_TRIANGLE_TO_RETURN = 0x11d,                     // OR ^ TO RETURN.
	LNG_UNUSED_11E = 0x11e,                                //
	LNG_UNUSED_11F = 0x11f,                                //
	LNG_UNUSED_120 = 0x120,                                //
	LNG_WARNING = 0x121,                                   // WARNING:
	LNG_FULL_MEMCARD_LINE1 = 0x122,                        // THE MEMORY CARD IN
	LNG_MEMORY_CARD_SLOT_1_IS_FULL = 0x123,                // MEMORY CARD SLOT 1 IS FULL.
	LNG_PLEASE_INSERT_A_MEMORY_CARD_THAT = 0x124,          // PLEASE INSERT A MEMORY CARD THAT
	LNG_HAS_AT_LEAST_2_BLOCKS_FREE_OR = 0x125,             // HAS AT LEAST 2 BLOCKS FREE OR
	LNG_USE_THE_CONSOLES_INTERNAL = 0x126,                 // USE THE CONSOLE'S INTERNAL
	LNG_MEMORY_CARD_MANAGER_TO_DELETE = 0x127,             // MEMORY CARD MANAGER TO DELETE
	LNG_SOME_BLOCKS_ON_THIS_MEMORY_CARD = 0x128,           // SOME BLOCKS ON THIS MEMORY CARD.
	LNG_UNUSED_129 = 0x129,                                //
	LNG_ERROR = 0x12a,                                     // ERROR:
	LNG_AN_ERROR_HAS_OCCURED_WHILE_READING = 0x12b,        // AN ERROR HAS OCCURED WHILE READING
	LNG_THE_MEMORY_CARD = 0x12c,                           // THE MEMORY CARD.
	LNG_UNUSED_12D = 0x12d,                                //
	LNG_MEMCARD_ERROR_PRESS_TO_CONTINUE = 0x12e,           // PRESS * TO CONTINUE
	LNG_PRESS_TRIANGLE_TO_RETURN = 0x12f,                  // PRESS ^ TO RETURN.
	LNG_UNUSED_130 = 0x130,                                //
	LNG_UNUSED_131 = 0x131,                                //
	LNG_UNUSED_132 = 0x132,                                //
	LNG_NO_DATA = 0x133,                                   // NO DATA
	LNG_THERE_IS_NO_CTR_DATA = 0x134,                      // THERE IS NO CTR DATA
	LNG_ON_THIS_MEMORY_CARD = 0x135,                       // ON THIS MEMORY CARD.
	LNG_UNUSED_136 = 0x136,                                //
	LNG_PLEASE_INSERT_ANOTHER_MEMORY_CARD = 0x137,         // PLEASE INSERT ANOTHER MEMORY CARD.
	LNG_UNUSED_138 = 0x138,                                //
	LNG_UNUSED_139 = 0x139,                                //
	LNG_UNUSED_13A = 0x13a,                                //
	LNG_UNUSED_13B = 0x13b,                                //
	LNG_RACE_FINISHED = 0x13c,                             // FINISHED!
	LNG_SAVE_COMPLETED = 0x13d,                            // SAVE COMPLETED.
	LNG_PLEASE_ENTER_YOUR_NAME = 0x13e,                    // PLEASE ENTER YOUR NAME
	LNG_SUBMIT_NAME_SAVE = 0x13f,                          // SAVE
	LNG_SAVE_HIGH_SCORE = 0x140,                           // SAVE HIGH SCORE
	LNG_CANCEL = 0x141,                                    // CANCEL
	LNG_OVERALL = 0x142,                                   // OVERALL
	LNG_LOSER = 0x143,                                     // LOSER!
	LNG_OPTIONS_TITLE = 0x144,                             // OPTIONS
	LNG_VIBRATE_ON = 0x145,                                // VIBRATE ON
	LNG_VIBRATE_OFF = 0x146,                               // VIBRATE OFF
	LNG_FX = 0x147,                                        // FX:
	LNG_MUSIC = 0x148,                                     // MUSIC:
	LNG_VOICE = 0x149,                                     // VOICE:
	LNG_DUAL_SHOCK = 0x14a,                                // DUAL SHOCK:
	LNG_OPTIONS_EXIT = 0x14b,                              // EXIT
	LNG_MODE = 0x14c,                                      // MODE:
	LNG_MONO = 0x14d,                                      // MONO
	LNG_STEREO = 0x14e,                                    // STEREO
	LNG_VERSUS = 0x14f,                                    // VERSUS
	LNG_CONFIGURE_ANALOG = 0x150,                          // CONFIGURE ANALOG:
	LNG_CONTROLLER_1 = 0x151,                              // CONTROLLER 1
	LNG_CONTROLLER_2 = 0x152,                              // CONTROLLER 2
	LNG_CONTROLLER_1A = 0x153,                             // CONTROLLER 1A
	LNG_CONTROLLER_1B = 0x154,                             // CONTROLLER 1B
	LNG_CONTROLLER_1C = 0x155,                             // CONTROLLER 1C
	LNG_CONTROLLER_1D = 0x156,                             // CONTROLLER 1D
	LNG_YOU_HIT = 0x157,                                   // YOU HIT
	LNG_HIT_YOU = 0x158,                                   // HIT YOU
	LNG_DIFFICULTY = 0x159,                                // DIFFICULTY
	LNG_EASY = 0x15a,                                      // EASY
	LNG_MEDIUM = 0x15b,                                    // MEDIUM
	LNG_HARD = 0x15c,                                      // HARD
	LNG_RACE_TYPE = 0x15d,                                 // RACE TYPE
	LNG_SINGLE = 0x15e,                                    // SINGLE
	LNG_CUP = 0x15f,                                       // CUP
	LNG_RELIC_AWARDED = 0x160,                             // RELIC AWARDED!
	LNG_NEW_HIGH_SCORE = 0x161,                            // NEW HIGH SCORE!
	LNG_PERFECT = 0x162,                                   // PERFECT
	LNG_RIPPER_ROOS_CHALLENGE = 0x163,                     // RIPPER ROO'S CHALLENGE
	LNG_PAPU_PAPUS_CHALLENGE = 0x164,                      // PAPU PAPU'S CHALLENGE
	LNG_KOMODO_JOES_CHALLENGE = 0x165,                     // KOMODO JOE'S CHALLENGE
	LNG_PINSTRIPES_CHALLENGE = 0x166,                      // PINSTRIPE'S CHALLENGE
	LNG_N_OXIDES_CHALLENGE = 0x167,                        // N. OXIDE'S CHALLENGE
	LNG_N_OXIDES_FINAL_CHALLENGE = 0x168,                  // N. OXIDE'S FINAL CHALLENGE
	LNG_GHOST_DATA_OVERFLOW = 0x169,                       // GHOST DATA OVERFLOW
	LNG_CAN_NOT_SAVE_GHOST_DATA = 0x16a,                   // CAN NOT SAVE GHOST DATA
	LNG_YOU_WIN = 0x16b,                                   // YOU WIN
	LNG_TRY_AGAIN = 0x16c,                                 // TRY AGAIN
	LNG_TIME_REMAINING = 0x16d,                            // TIME REMAINING
	LNG_BONUS_AWARDED = 0x16e,                             // BONUS AWARDED
	LNG_CTR_TOKEN_AWARDED = 0x16f,                         // CTR TOKEN AWARDED
	LNG_BEST_LAP = 0x170,                                  // BEST LAP
	LNG_BEST_TIMES = 0x171,                                // BEST TIMES
	LNG_NEW_BEST_LAP = 0x172,                              // NEW BEST LAP!
	LNG_N_TROPY_OPENED = 0x173,                            // N. TROPY OPENED!
	LNG_N_TROPY_BEATEN = 0x174,                            // YOU BEAT N. TROPY!
	LNG_TRACK = 0x175,                                     // TRACK
	LNG_CTR_CHALLENGE_TITLE = 0x176,                       // CTR CHALLENGE
	LNG_AKU_HINT_REPEAT_INSTRUCTIONS = 0x177,              // TO HEAR THIS HINT AGAIN PRESS THE START BUTTON AND CHOOSE AKU AKU HINTS
	LNG_AKU_AKU_HINTS_MENU = 0x178,                        // AKU AKU HINTS
	LNG_UKA_UKA_HINTS_MENU = 0x179,                        // UKA UKA HINTS
	LNG_HINT_EXIT = 0x17a,                                 // EXIT
	LNG_GREETINGS = 0x17b,                                 // GREETINGS!
	LNG_WELCOME_TO_THE_ADVENTURE_ARENA_YOU_CAN_TRAVEL =
	    0x17c,                    // WELCOME TO THE ADVENTURE ARENA.  YOU CAN TRAVEL AROUND THIS AREA AND PRACTICE YOUR DRIVING SKILLS.  THE DOT...
	LNG_USING_A_WARP_PAD = 0x17d, // USING A WARP PAD
	LNG_TO_ACCESS_A_RACE_TRACK_DRIVE_ONTO_A =
	    0x17e,                     // TO ACCESS A RACE TRACK, DRIVE ONTO A WARP PAD THAT HAS AN ACTIVE WARP VORTEX, AND IT WILL TAKE YOU TO THE T...
	LNG_ACCESSING_A_TRACK = 0x17f, // ACCESSING A TRACK
	LNG_TO_ACCESS_THIS_TRACK_YOU_MUST_FIRST_COLLECT =
	    0x180,                       // TO ACCESS THIS TRACK YOU MUST FIRST COLLECT THE NUMBER OF TROPHIES REQUIRED TO TURN ON THE WARP PAD.  TO GE...
	LNG_USING_A_BOSS_GARAGE = 0x181, // USING A BOSS GARAGE
	LNG_TO_ACCESS_THIS_BOSS_GARAGE_YOU_MUST_COME = 0x182, // TO ACCESS THIS BOSS GARAGE, YOU MUST COME IN FIRST PLACE IN ALL FOUR RACES OF THIS AREA.
	LNG_ENTERING_OXIDES_SPACE_SHIP = 0x183,               // ENTERING OXIDE'S SPACE SHIP
	LNG_YOU_DONT_HAVE_THE_FOUR_BOSS_KEYS_TO =
	    0x184,                       // YOU DON'T HAVE THE FOUR BOSS KEYS TO OPEN THIS DOOR.  BEAT EACH BOSS TO GET A KEY, AND WHEN YOU HAVE ALL FO...
	LNG_OPENING_WORLD_DOORS = 0x185, // OPENING WORLD DOORS
	LNG_YOU_MUST_HAVE_A_BOSS_KEY_TO_OPEN =
	    0x186,                    // YOU MUST HAVE A BOSS KEY TO OPEN THIS DOOR.  YOU CAN RACE A BOSS AFTER BEATING ALL FOUR TRACKS IN AN AREA. ...
	LNG_LOAD_SAVE_SCREEN = 0x187, // LOAD-SAVE SCREEN
	LNG_THIS_IS_THE_LOAD_SAVE_SCREEN_THERE_ARE =
	    0x188,                      // THIS IS THE LOAD-SAVE SCREEN.  THERE ARE FIVE OF THESE SCREENS, ONE IN EACH WORLD SECTION.  WHEN YOU WANT T...
	LNG_NEW_WORLD_GREETING = 0x189, // NEW WORLD GREETING
	LNG_CONGRATULATIONS_ON_OPENING_THIS_NEW_AREA_HERE_YOU =
	    0x18a, // CONGRATULATIONS ON OPENING THIS NEW AREA!  HERE YOU WILL FIND FOUR MORE TRACKS TO RACE.  GOOD LUCK!
	LNG_NO_MEMORYU_CARD_IN_MEMORY_CARD_SLOT_WARNING = 0x18b, // NO MEMORYU CARD IN MEMORY CARD SLOT WARNING
	LNG_THERE_ARE_NO_MEMORY_CARDS_IN_ANY_OF =
	    0x18c,                            // THERE ARE NO MEMORY CARDS IN ANY OF THE MEMORY CARD SLOTS.  PUT A MEMORY CARD IN A MEMORY CARD SLOT AND TRY...
	LNG_MEMORY_CARD_FULL_WARNING = 0x18d, // MEMORY CARD FULL WARNING
	LNG_THE_CURRENT_MEMORY_CARD_IS_FULL_PUT_IN =
	    0x18e, // THE CURRENT MEMORY CARD IS FULL.  PUT IN A DIFFERENT MEMORY CARD OR DELETE BLOCKS FROM THE CURRENT MEMORY C...
	LNG_NO_CRASH_DATA_ON_MEMORY_CARD_WARNING = 0x18f,  // NO CRASH DATA ON MEMORY CARD WARNING
	LNG_THERE_IS_NO_CRASH_TEAM_RACING_DATA_ON = 0x190, // THERE IS NO CRASH TEAM RACING DATA ON THIS MEMORY CARD.
	LNG_NO_CONTROLLER_WARNING = 0x191,                 // NO CONTROLLER WARNING
	LNG_NO_CONTROLLERS_ARE_PLUGGED_INTO_CONTROLLER_PORTS_PLEASE =
	    0x192,                                    // NO CONTROLLERS ARE PLUGGED INTO CONTROLLER PORTS.  PLEASE INSERT A CONTROLLER INTO A CONTROLLER PORT.
	LNG_WHEN_PLAYER_WINS_A_TROPHY = 0x193,        // WHEN PLAYER WINS A TROPHY
	LNG_CONGRATULATIONS_YOU_WIN_A_TROPHY = 0x194, // CONGRATULATIONS!  YOU WIN A TROPHY!
	LNG_WHEN_PLAYER_WINS_A_BOSS_KEY = 0x195,      // WHEN PLAYER WINS A BOSS KEY
	LNG_GOOD_JOB_YOUVE_EARNED_A_KEY = 0x196,      // GOOD JOB, YOU'VE EARNED A KEY!
	LNG_HANG_TIME_HINT = 0x197,                   // HANG TIME HINT
	LNG_YOU_CAN_GET_A_HANG_TIME_TURBO_FROM =
	    0x198,                      // YOU CAN GET A HANG TIME TURBO FROM JUMPING.  THE LONGER YOU'RE IN THE AIR, THE BIGGER THE TURBO YOU'LL GET ...
	LNG_POWER_SLIDING_HINT = 0x199, // POWER SLIDING HINT
	LNG_YOU_CAN_GO_FASTER_THROUGH_TURNS_BY_POWER =
	    0x19a,                    // YOU CAN GO FASTER THROUGH TURNS BY POWER SLIDING.  TO ACCESS THE POWER SLIDE, PRESS AND HOLD THE R1 BUTTON ...
	LNG_TURBO_BOOST_HINT = 0x19b, // TURBO BOOST HINT
	LNG_TO_GET_A_TURBO_BOOST_WHILE_POWER_SLIDING =
	    0x19c,                    // TO GET A TURBO BOOST WHILE POWER SLIDING, WAIT UNTIL THE SMOKE FROM YOUR EXHAUST TURNS BLACK, THEN PRESS TH...
	LNG_BRAKE_SLIDE_HINT = 0x19d, // BRAKE SLIDE HINT
	LNG_TO_GET_AROUND_A_TIGHT_TURN_OR_TO =
	    0x19e,                             // TO GET AROUND A TIGHT TURN, OR TO FACE A DIRECTION QUICKLY, USE THE BRAKE SLIDE BY PRESSING AND HOLDING THE...
	LNG_DOUBLE_LOCKED_WORLD_DOORS = 0x19f, // DOUBLE LOCKED WORLD DOORS
	LNG_YOU_MUST_HAVE_TWO_BOSS_KEYS_TO_OPEN =
	    0x1a0,                               // YOU MUST HAVE TWO BOSS KEYS TO OPEN THIS DOOR.  YOU CAN RACE A BOSS AFTER BEATING ALL FOUR TRACKS IN AN ARE...
	LNG_WHEN_PLAYER_WINS_A_RELIC = 0x1a1,    // WHEN PLAYER WINS A RELIC
	LNG_GREAT_YOUVE_EARNED_A_RELIC = 0x1a2,  // GREAT, YOU'VE EARNED A RELIC!
	LNG_WHEN_PLAYER_WINS_A_CTR_COIN = 0x1a3, // WHEN PLAYER WINS A CTR COIN
	LNG_EXCELLENT_WORK_YOUVE_COLLECTED_A_CTR_TOKEN = 0x1a4, // EXCELLENT WORK, YOU'VE COLLECTED A CTR TOKEN!
	LNG_WHEN_PLAYER_WINS_A_GEM = 0x1a5,                     // WHEN PLAYER WINS A GEM
	LNG_CONGRATULATIONS_YOUVE_WON_A_GEM = 0x1a6,            // CONGRATULATIONS, YOU'VE WON A GEM!
	LNG_WUMPA_FRUIT_HINT = 0x1a7,                           // WUMPA FRUIT HINT
	LNG_THE_MORE_WUMPA_FRUIT_YOU_COLLECT_THE_FASTER =
	    0x1a8,            // THE MORE WUMPA FRUIT YOU COLLECT, THE FASTER YOUR KART WILL GO.  IF YOU COLLECT AND HOLD 10 WUMPA FRUIT YOU...
	LNG_TNT_HINT = 0x1a9, // TNT HINT
	LNG_WHEN_YOU_GET_A_TNT_CRATE_ON_YOUR =
	    0x1aa,                   // WHEN YOU GET A TNT CRATE ON YOUR HEAD, START HOPPING IMMEDIATELY.  IF YOU REACT FAST, AND HOP ENOUGH TIMES,...
	LNG_MAP_INFORMATION = 0x1ab, // MAP INFORMATION
	LNG_THE_DOTS_AND_STARS_ON_THE_MAP_REPRESENT =
	    0x1ac,                // THE DOTS AND STARS ON THE MAP REPRESENT WARP PADS WHICH LEAD TO RACES.  WHEN THEY FLASH, IT SIGNIFIES THEY ...
	LNG_BONUS_ROUNDS = 0x1ad, // BONUS ROUNDS
	LNG_COLLECT_EVERY_CRYSTAL_IN_THE_ARENA_BEFORE_THE =
	    0x1ae,                            // COLLECT EVERY CRYSTAL IN THE ARENA BEFORE THE TIME RUNS OUT.  IF YOU CAN GET THEM ALL, YOU WILL WIN A PRIZE!
	LNG_CTR_CHALLENGE_HINT_TITLE = 0x1af, // CTR CHALLENGE
	LNG_COLLECT_THE_LETTERS_C_T_AND_R_ON =
	    0x1b0,                       // COLLECT THE LETTERS C, T, AND R ON EACH TRACK AND COME IN FIRST PLACE TO WIN A CTR TOKEN.  BEWARE, SOME LET...
	LNG_GEM_CUPS_HINT_TITLE = 0x1b1, // GEM CUPS
	LNG_IF_YOU_COLLECT_FOUR_CTR_TOKENS_OF_THIS =
	    0x1b2,                 // IF YOU COLLECT FOUR CTR TOKENS OF THIS COLOR, YOU CAN ENTER THE GEM CUP.  SCORE THE MOST POINTS IN THE FOUR...
	LNG_SECRET_TRACKS = 0x1b3, // SECRET TRACKS
	LNG_YOU_MUST_FIRST_COLLECT_THE_REQUIRED_NUMBER_OF = 0x1b4, // YOU MUST FIRST COLLECT THE REQUIRED NUMBER OF RELICS TO RACE THIS TRACK.
	LNG_RELIC_RACE_HINT_TITLE = 0x1b5,                         // RELIC RACE
	LNG_GET_THE_LOWEST_TIME_YOU_CAN_BY_RACING =
	    0x1b6,                        // GET THE LOWEST TIME YOU CAN BY RACING FAST AND BREAKING TIME CRATES.  EACH TIME CRATE YOU BREAK WILL FREEZE...
	LNG_UNUSED_1B7 = 0x1b7,           //
	LNG_HOP_HAPPY = 0x1b8,            // HOP HAPPY
	LNG_RARE_AIR = 0x1b9,             // RARE AIR
	LNG_WALLFLOWER = 0x1ba,           // WALLFLOWER
	LNG_MISSILE_MAGNET = 0x1bb,       // MISSILE MAGNET
	LNG_MOST_BOMBED = 0x1bc,          // MOST BOMBED
	LNG_WHATS_A_PICKUP = 0x1bd,       // WHAT'S A PICKUP?
	LNG_SLOWPOKE = 0x1be,             // SLOWPOKE
	LNG_MOST_DIZZY = 0x1bf,           // MOST DIZZY
	LNG_SITTING_DUCK = 0x1c0,         // SITTING DUCK
	LNG_DRIVERS_CHUMP = 0x1c1,        // %S'S CHUMP
	LNG_BAD_SHOT = 0x1c2,             // BAD SHOT
	LNG_FALL_GUY = 0x1c3,             // FALL GUY
	LNG_LEAST_FRUIT = 0x1c4,          // LEAST FRUIT
	LNG_MINE_SWEEPER = 0x1c5,         // MINE SWEEPER
	LNG_MUD_DOG = 0x1c6,              // MUD DOG
	LNG_PLANT_FOOD = 0x1c7,           // PLANT FOOD
	LNG_MOST_BURNED = 0x1c8,          // MOST BURNED
	LNG_FLATMAN = 0x1c9,              // FLATMAN
	LNG_MR_REVERSE = 0x1ca,           // MR. REVERSE
	LNG_SKID_SQUID = 0x1cb,           // SKID SQUID
	LNG_TURBO_MASTER = 0x1cc,         // TURBO MASTER
	LNG_SUPER_SLIDER = 0x1cd,         // SUPER SLIDER
	LNG_MOST_AIR_TIME = 0x1ce,        // MOST AIR TIME
	LNG_BIGGEST_AIR = 0x1cf,          // BIGGEST AIR
	LNG_BEAKER_ACE = 0x1d0,           // BEAKER ACE
	LNG_MISSILE_MASTER = 0x1d1,       // MISSILE MASTER
	LNG_CRATES_R_US = 0x1d2,          // CRATES 'R' US
	LNG_FASTEST_RACER = 0x1d3,        // FASTEST RACER
	LNG_KING_OF_THE_PACK = 0x1d4,     // KING OF THE PACK
	LNG_UNTOUCHABLE = 0x1d5,          // UNTOUCHABLE
	LNG_BEST_AIM = 0x1d6,             // BEST AIM
	LNG_LONGEST_SHOT = 0x1d7,         // LONGEST SHOT
	LNG_MOST_JUICED_UP = 0x1d8,       // MOST JUICED UP
	LNG_FRUIT_HOG = 0x1d9,            // FRUIT HOG
	LNG_COMEBACK_KID_AWARD = 0x1da,   // COMEBACK KID
	LNG_CLOCK_JOCK = 0x1db,           // CLOCK JOCK
	LNG_SPEED_DEMON = 0x1dc,          // SPEED DEMON!
	LNG_STEAMROLLER = 0x1dd,          // STEAMROLLER
	LNG_OUT_OF_GAS = 0x1de,           // OUT OF GAS!
	LNG_TAKE_A_BREAK = 0x1df,         // TAKE A BREAK!
	LNG_NOT_BAD = 0x1e0,              // NOT BAD
	LNG_HAVING_FUN = 0x1e1,           // HAVING FUN?
	LNG_BATTLE_SCARS = 0x1e2,         // BATTLE SCARS?
	LNG_NO_COMMENT = 0x1e3,           // NO COMMENT...
	LNG_CRASH_MUCH = 0x1e4,           // CRASH MUCH?
	LNG_FEELING_DIZZY = 0x1e5,        // FEELING DIZZY?
	LNG_TOASTED = 0x1e6,              // TOASTED!
	LNG_BIG_ZERO = 0x1e7,             // BIG ZERO!
	LNG_SCORELESS_WONDER = 0x1e8,     // SCORELESS WONDER!
	LNG_DEAD_LAST = 0x1e9,            // DEAD LAST
	LNG_TIME_TO_RETIRE = 0x1ea,       // TIME TO RETIRE!
	LNG_FLOWER_CHILD = 0x1eb,         // FLOWER CHILD!
	LNG_NOTHING_DOING = 0x1ec,        // NOTHING DOING
	LNG_LOST_IN_SPACE = 0x1ed,        // LOST IN SPACE
	LNG_REST_IN_PIECES = 0x1ee,       // REST IN PIECES
	LNG_CLUELESS = 0x1ef,             // CLUELESS
	LNG_PUNCH_DRUNK = 0x1f0,          // PUNCH DRUNK
	LNG_ASLEEP_AT_WHEEL = 0x1f1,      // ASLEEP AT WHEEL
	LNG_KEEP_THE_DAY_JOB = 0x1f2,     // KEEP THE DAY JOB
	LNG_ROAD_KILL = 0x1f3,            // ROAD KILL
	LNG_MAKE_A_WISH = 0x1f4,          // MAKE A WISH!
	LNG_SQUASHED_BUG = 0x1f5,         // SQUASHED BUG!
	LNG_NOTHIN_BUT_DEAD = 0x1f6,      // NOTHIN' BUT DEAD!
	LNG_K_I_A_A_S_A_P = 0x1f7,        // K.I.A. A.S.A.P.
	LNG_STUFFED_TURKEY = 0x1f8,       // STUFFED TURKEY
	LNG_YOURE_TOAST = 0x1f9,          // YOU'RE TOAST!
	LNG_INSURANCE_RISK = 0x1fa,       // INSURANCE RISK!
	LNG_ON_ICE = 0x1fb,               // ON ICE!
	LNG_LICENSE_REVOKED = 0x1fc,      // LICENSE REVOKED!
	LNG_JUST_SQUEAL = 0x1fd,          // JUST SQUEAL!
	LNG_MOSTLY_DEAD = 0x1fe,          // MOSTLY DEAD
	LNG_WHAT_HAPPENED = 0x1ff,        // WHAT HAPPENED?
	LNG_HARD_KNOCKS = 0x200,          // HARD KNOCKS
	LNG_BLACK_N_BLUE = 0x201,         // BLACK 'N BLUE
	LNG_BUTTON_PROBLEMS = 0x202,      // BUTTON PROBLEMS?
	LNG_WHERES_THE_BEEF = 0x203,      // WHERE'S THE BEEF?
	LNG_SO_CLOSE = 0x204,             // SO CLOSE!
	LNG_SECOND_FIDDLE = 0x205,        // SECOND FIDDLE
	LNG_BRIDES_MAID = 0x206,          // BRIDE'S MAID
	LNG_ILL_BE_BACK = 0x207,          // I'LL BE BACK!
	LNG_NEARLY_FAMOUS = 0x208,        // NEARLY FAMOUS
	LNG_IF_ONLY = 0x209,              // IF ONLY...
	LNG_MAYBE_NEXT_TIME = 0x20a,      // MAYBE NEXT TIME!
	LNG_SILVER_MEDAL = 0x20b,         // SILVER MEDAL
	LNG_SMACK_MAN = 0x20c,            // SMACK MAN
	LNG_RING_KING = 0x20d,            // RING KING!
	LNG_TOP_GUN = 0x20e,              // TOP GUN!
	LNG_WHEELED_WARRIOR = 0x20f,      // WHEELED WARRIOR
	LNG_TOP_DOG = 0x210,              // TOP DOG!
	LNG_BRAGGING_RIGHTS = 0x211,      // BRAGGING RIGHTS!
	LNG_GETS_THE_GOLD = 0x212,        // GETS THE GOLD!
	LNG_LAST_STANDING = 0x213,        // LAST STANDING!
	LNG_CONQUERED_ALL = 0x214,        // CONQUERED ALL!
	LNG_HIT_N_RUN = 0x215,            // HIT N' RUN!
	LNG_KNOCK_OUT = 0x216,            // KNOCK OUT!
	LNG_WINNER = 0x217,               // WINNER!
	LNG_YOU_ROCK = 0x218,             // YOU ROCK!
	LNG_DISASTER_MASTER = 0x219,      // DISASTER MASTER!
	LNG_THE_DOMINATOR = 0x21a,        // THE DOMINATOR!
	LNG_COMEBACK_KID_COMMENT = 0x21b, // COMEBACK KID!
	LNG_GAVE_IT_AWAY = 0x21c,         // GAVE IT AWAY!
	LNG_DEATH_TOUCH = 0x21d,          // DEATH TOUCH!
	LNG_ACID_RAINMAN = 0x21e,         // ACID RAINMAN!
	LNG_BULLS_EYE = 0x21f,            // BULL'S EYE!
	LNG_EASY_MONEY = 0x220,           // EASY MONEY!
	LNG_FISH_IN_A_BARREL = 0x221,     // FISH IN A BARREL!
	LNG_CENTER_THE_CONTROLLER_AND_PRESS_BUTTON = 0x222,         // CENTER THE CONTROLLER\rAND PRESS *
	LNG_SELECT_DEAD_ZONE_AND_PRESS_BUTTON = 0x223,              // SELECT DEAD ZONE\rAND PRESS *
	LNG_0 = 0x224,                                              // 0
	LNG_3 = 0x225,                                              // 3
	LNG_5 = 0x226,                                              // 5
	LNG_7 = 0x227,                                              // 7
	LNG_SELECT_RANGE_AND_PRESS_BUTTON = 0x228,                  // SELECT RANGE\rAND PRESS *
	LNG_30 = 0x229,                                             // 30
	LNG_45 = 0x22a,                                             // 45
	LNG_90 = 0x22b,                                             // 90
	LNG_135 = 0x22c,                                            // 135
	LNG_180 = 0x22d,                                            // 180
	LNG_FINAL = 0x22e,                                          // FINAL
	LNG_GEM_CUPS_LABEL = 0x22f,                                 // GEM CUPS:
	LNG_DEMO_MODE_PRESS_ANY_BUTTON_TO_EXIT = 0x230,             // DEMO MODE\rPRESS ANY BUTTON TO EXIT
	LNG_LOADING = 0x231,                                        // LOADING...
	LNG_TO_HEAR_THIS_HINT_AGAIN_PRESS_THE_START = 0x232,        // TO HEAR THIS HINT AGAIN PRESS THE START BUTTON AND CHOOSE UKA UKA HINTS
	LNG_FINAL_LAP = 0x233,                                      // FINAL LAP!
	LNG_SCRAPBOOK = 0x234,                                      // Scrapbook
	LNG_SAVE_GAME = 0x235,                                      // SAVE GAME?
	LNG_SAVE_YOUR_CUP_PROGRESS = 0x236,                         // SAVE YOUR CUP PROGRESS?
	LNG_SAVE_YOUR_CUP_PROGRESS_NEW_BATTLE_ARENA_OPENED = 0x237, // SAVE YOUR CUP PROGRESS?\r\rNEW BATTLE ARENA OPENED!
	LNG_YOU_CRAZY_ENOUGH_TO_RACE_ME = 0x238,                    // You CRAZY enough to race me?
	LNG_I_SHOULD_FACE_OXIDE_IN_THE_BIG_RACE = 0x239,            // I should face Oxide\rin the big race.
	LNG_IM_THE_ONLY_ONE_CRAZY_ENOUGH_TO_THINK = 0x23a,          // I'm the only one CRAZY enough\rto think I can beat him!
	LNG_ILL_SHOW_YOU_WILD_DRIVING = 0x23b,                      // I'll show you wild driving!
	LNG_LAST_ONE_ACROSS_THE_FINISH_LINE_IS_A = 0x23c,           // Last one across the finish\rline is a rotten brain!
	LNG_YOU_ARE_CRAZIER_THAN_ME = 0x23d,                        // You ARE crazier than me!
	LNG_BEST_HEAD_GET_CHECKED_IF_YOU_THINK_YOU = 0x23e,         // Best head get checked if you\rthink you can beat Oxide.
	LNG_HAVE_A_KEY = 0x23f,                                     // Have a key.
	LNG_GOOD_LUCK_YOULL_NEED_IT = 0x240,                        // Good luck!  You'll need it!
	LNG_NA_241 = 0x241,                                         // na
	LNG_NA_242 = 0x242,                                         // na
	LNG_NA_243 = 0x243,                                         // na
	LNG_TM = 0x244,                                             // TM
	LNG_SPEED = 0x245,                                          // Speed
	LNG_ACCEL = 0x246,                                          // Accel
	LNG_TURN = 0x247,                                           // Turn
	LNG_BEGINNER = 0x248,                                       // Beginner
	LNG_INTERMEDIATE = 0x249,                                   // Intermediate
	LNG_ADVANCED = 0x24a,                                       // Advanced
	LNG_TURBOS = 0x24b,                                         // Turbos
};

#endif
